### PR TITLE
Add missing env vars to docker compose setup

### PR DESCRIPTION
**Pull request by ajmaddaford**
### What is the context of this PR?
Adds missing environment variables to docker compose file. The defaults for these were recently removed from survey runner.
 
### How to review 
Follow Docker instructions in the Readme and check the app works.

### CODE REVIEW

**Review by adoublebarrel — APPROVED** [review]
Makes sense.

**Review by samiwel — APPROVED** [review]
Looks okay to me.

**Review by dcdarrell9 — APPROVED** [review]

**Comment by jonnyshaw89** [comment]
@ajmaddaford won't this stop working as soon as the secrets from file is in?

**Comment by armstrongb** [comment]
It works for my environment so... LGTM

**Pull request merged**
