### PR TITLE
Upgrade python Cryptography and Cffi to latest versions

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
Upgraded Cryptography and Cffi to latest versions to fix the issues observed in production.
Have also removed the previous workaround
Have deployed and tested in AWS

### CODE REVIEW

**Comment by collisdigital** [comment]
Do we want to check what version of OpenSSL EB uses by default and also consider if it is something we need to manually upgrade on deployment?

**Comment by collisdigital** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/openssl/

**Comment by collisdigital** [comment]
From https://www.openssl.org/ 

> 2-Jan-2017The OpenSSL 1.0.1 series of releases are now out of support. Please upgrade to 1.1.0 or 1.0.2.

**Comment by jonnyshaw89** [comment]
@collisdigital EB is running `OpenSSL 1.0.1k-fips 8 Jan 2015`

**Comment by jonnyshaw89** [comment]
OpenSSL 1.1.0 or 1.0.2 are not yet available in Amazon Linux AMI

**Comment by collisdigital** [comment]
Ok at least we know; will monitor security bulletins to know when it's upgraded

**Review by ajmaddaford — APPROVED** [review]

**Review by benjefferies — APPROVED** [review]

**Pull request merged**
