### PR TITLE
Use ChromeHeadless for old function tests

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
The old functional tests are currently using PhantomJS. This is not very stable and causes issues in Travis and Concourse.

### How to review 
Do the tests run properly in Travis and Concourse?

### CODE REVIEW

**Comment by yoganandkunche** [comment]
@jonnyshaw89 seems to be working fine in headless mode but looks like it is now taking longer to build and run tests not sure if it is related.

**Comment by yoganandkunche** [comment]
@jonnyshaw89 squishy squashy ?

**Review by yoganandkunche — APPROVED** [review]
LGTM :+1:

**Review by jcox-dev — APPROVED** [review]
Works fine locally and travis seems happy with it 👍

**Pull request merged**
