### PR TITLE
Moved static content up a directory

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?

Currently the docker container builds the static assets but when the volume was mounted it lost the compiled assets.
This change moves those static assets so they they are no longer in the app directory
### How to review

When building the docker containers from a clean checkout, does your application have styles when running?

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
Confirmed working on ElasticBeanstalk

**Review by hamishtaplin — CHANGES_REQUESTED** [review]
@jonnyshaw89 Line 77 of README needs updating

**Comment by hamishtaplin** [comment]
@jonnyshaw89 Also, the location of the system-generated `_sprite.scss` is wrong throughout. Is it worth fixing that as part of this? If so, I can push those changes up.

**Comment by benjefferies** [comment]
It's not directly related to this but it might be worth adding instructions how to remotely debug within the docker container if you found out in the end

**Review by hamishtaplin — APPROVED** [review]

**Pull request merged**
