### PR TITLE
Codecov Fixes from Codecov Support

### PR DESCRIPTION
**Pull request by collisdigital**
### What is the context of this PR?

Steve from Codecov support as provided this PR to resolve issues we are experiencing with codecov. There was no need to install the python package, the bash script manages the whole process.
### How to review

Verify that Travis CI correctly uploads codecov coverage and it is reported in PRs.
### Who worked on the PR

@stevepeak (Codecov Support)

### CODE REVIEW

**Comment by stevepeak** [comment]
Thank you @collisdigital feel free to ping me if you have questions. I'll be happy to review any issue or help answer questions.

Extra credit: there is a lot of customization available to Codecov. Learn more at http://docs.codecov.io/docs/codecov-yaml

**Comment by collisdigital** [comment]
@stevepeak we also have 

```
# fail travis if under X% test coverage
- coverage report --fail-under=77
```

on line 23, is that correct?

**Comment by collisdigital** [comment]
@stevepeak also codecov is setup as an integration to GitHub but isn't available as a status check (see above; only Travis CI is there); we previously had it listed as a status check (not sure how we enabled it now since I cannot see it as an option in the repo settings anymore) but it wasn't being reported correctly (hence blocking the PR from being merged.

Does codecov support being a status check on PRs and if so, do you have any idea why it isn't available for this repo?

**Comment by stevepeak** [comment]
@collisdigital this is now handled by Commit Status API: http://docs.codecov.io/docs/commit-status

I'll check to see why the statuses are not posting.

**Comment by stevepeak** [comment]
@collisdigital status did not post because the current use @warrenbailey is being used to set the status and got a denied access to GH API's. See this article on how to set a new bot http://docs.codecov.io/docs/team-bot

**Comment by collisdigital** [comment]
Thanks @stevepeak I've changed the config as suggested and also raised a separate PR for some tweaks based on the docs you pointed at #420. Hopefully that will solve this issue.

**Comment by collisdigital** [comment]
LGTM 👍

**Pull request merged**
