### PR TITLE
Switch to summary-type census submission block

### PR DESCRIPTION
**Pull request by bambrp**
### What is the context of this PR?
Switched from a fixed text based confirmation screen to an automatic summary as the survey submission screen.

### How to review 
Checkout branch, run through an individual census (eng/wal or ni), and check final summary page reflects the answers you provided.

### CODE REVIEW

**Review by iwootten — APPROVED** [review]

**Review by iwootten — CHANGES_REQUESTED** [review]
This seems to be applied to wls/nir, where the card says it should be for eng?

**Review by MebinAbraham — COMMENTED** [review]
If both surveys now don't use confirmation, `confirmation.json` file can be removed?

**Comment by bambrp** [comment]
> If both surveys now don't use confirmation, `confirmation.json` file can be removed?

I don't see any other uses of it, so it could- I just wasn't sure if that was premature, and if we'd be happy to have the text content of it easily to hand, but I suppose that's what histories are for.

**Review by iwootten — APPROVED** [review]
Approving this based on @charlotte-hirst saying it can be applied to all versions.

**Comment by MebinAbraham** [comment]
@bambrp I don't see a reason to keep it if it is not used. Git history is always here if it is ever needed I guess.

**Review by berroar — APPROVED** [review]
Tested the changes, all looks okay to me.

**Comment by bitdivision** [comment]
@MebinAbraham removed as part of https://github.com/ONSdigital/eq-survey-runner/pull/2104/files

**Review by MebinAbraham — APPROVED** [review]

**Pull request merged**
