### PR TITLE
Eq 744 cleanse input into survey runner

### PR DESCRIPTION
**Pull request by adoublebarrel**
### What is the context of this PR?

Reworked the way user input is sanitised so that is clearer and cleaner. Moved all HTML encoding to the point where schema context generation happens and turned off autoescaping for theme templates, see card for more details.

[Trello Card](https://trello.com/c/FsZ1ute6/744-cleanse-input-into-survey-runner)

### How to review 

- All Existing functionality should be intact
- There should be no vectors for XSS via user input

### CODE REVIEW

**Review by collisdigital — COMMENTED** [review]
Is there a way to disable the `safe` filter in jinja2 so we don't use it by accident (or do we actually use it elsewhere)?

**Comment by adoublebarrel** [comment]
Not in a nice way, we could override it in the filters dict of Jinjas environment but that's not very explicit which could cause someone a nasty surprise in the future.

The safe filter wont have any affect in the theme templates now that autoescaping is turned off, as effectively that says we consider the entire Jinja context to be 'safe'. So at worst it's a little extra processing.

We do need to make sure that everyone who is onboard/comes onboard is aware that autoescaping is turned off in the theme templates (because they consume system generated HTML content).  As well as knowing the safe filter is unnecessary it means that introducing user input outside of schema_context generation is a no, no.

**Comment by ajmaddaford** [comment]
There places in the templates we use the metadata context e.g. introduction.html. These values aren't escaped or made json safe. It might also be worth reviewing the duplication of values in schema_context and metadata_context.

**Review by ajmaddaford — DISMISSED** [review]

**Comment by jonnyshaw89** [comment]
screen shot 2017-05-22 at 15 44 45
I Broke it

**Comment by jonnyshaw89** [comment]
I entered `<script>alert('gotcha')</script>` into `test_textfield.json`

**Review by jonnyshaw89 — APPROVED** [review]

**Review by ajmaddaford — APPROVED** [review]

**Pull request merged**
