### PR TITLE
Print styles

### LINKED ISSUE #1102: Print styles
### Expected behaviour
Print document shouldn't contain navigation elements  

### Actual behaviour
Print document contains navigational elements

### Steps to reproduce the behaviour
Select file and then print

### PR DESCRIPTION
**Pull request by bennpearson**
### What is the context of this PR?
Fixes #1102 

### How to review 

- Select `file >> print` in the browser menu
- Check all buttons are hidden
- Check in different browsers

### CODE REVIEW

**Comment by bennpearson** [comment]
Ink saving font: https://rymaneco.co.uk/

**Comment by ajmaddaford** [comment]
The summary screen doesn't have a visible table outline:
image

**Comment by bennpearson** [comment]
I removed the tables as they was causing text to be cut off. This also made the page shorter; saving paper and ink  🌳  ✌️

**Comment by collisdigital** [comment]
@bennpearson I need to talk with @armstrongb about this, I'm not sure that's a winner.

**Comment by armstrongb** [comment]
I agree with @collisdigital that we should restore the tables to preserve the layout.
I would suggest something like the screenshot below where each question has a bottom border but all others are removed and we use padding below each response to give visual structure.

If possible I would like to introduce a reminder for print that would state that these are unsubmitted answers and remind the respondent that there is a remaining action before completion. Using a warning or error panel style to give it a strong presence. I'm also considering reducing the `.summary__question` colour to `#666` - saving ink _@bennpearson_ but also making the answers more prominent.

Whether this is using CSS to insert content or if the content is in the html will require discussion with @hamishtaplin and @bennpearson.

For example:
`@media print {
    h1.saturn:after {
        content:"Please remember to submit these responses.";
        font-size:1.3rem;
        display:block;
        border-left:7px solid #d0121E;
        background:#fbecec;
        padding:1rem;
        margin: 1rem 0 1rem -0.5rem;
    }
    .summary__items {
        border-bottom: 1px solid #999 !important;
        border-radius: 0;
        padding:0 0 0.5rem 0.5rem;
    }
    .summary__question {
        padding: 0.5rem 0 0 0 !important;
    }
}`

ons-screenshot-summary-print-draft-26042017

**Comment by collisdigital** [comment]
+1 for Ben's design above, @bennpearson can it be done?

**Review by collisdigital — CHANGES_REQUESTED** [review]
Align with BenA's design

**Comment by bennpearson** [comment]
Yes this new style looks good. Not sure about putting content into the css though. How about putting it in the schema? That would help with language support too.

**Comment by collisdigital** [comment]
Put the content in the template HTML but hide with css?

**Comment by bennpearson** [comment]
Yes. What do you think @hamishtaplin

**Comment by armstrongb** [comment]
Can the inputs be indented as per the visual below and the distance between inputs reduced?

ons-screenshot-summary-print-draft-26042017

**Comment by armstrongb** [comment]
Can we now add a warning panel as per the screenshot below and amend the copy to the following?

> Please check your responses carefully before submitting.

ons-screenshot-summary-warning-draft-20170502

This shouldn't be a link to the submit button as we want the respondent to review the responses not skip past them.

**Comment by collisdigital** [comment]
Based on our semantic change card, shouldn't that warning be the H1 now?

**Comment by armstrongb** [comment]
Good point - I'll review this morning and update.

**Comment by collisdigital** [comment]
On mobile when navigation is shown the viewport is grey'd out, this applies on the print out too, please fix!

**Comment by collisdigital** [comment]
@bennpearson all done? If so I'll review again with @armstrongb now

**Comment by bennpearson** [comment]
Yes please

**Review by collisdigital — APPROVED** [review]
Looks good now, can you squash and rebase

**Comment by collisdigital** [comment]
@hamishtaplin do you approve this one?

**Review by armstrongb — APPROVED** [review]

**Review by hamishtaplin — APPROVED** [review]

**Pull request merged**
