### PR TITLE
Add more debug to failing selenium tests

### PR DESCRIPTION
**Pull request by benjefferies**
### What is the context of this PR?
It is hard to understand why a test failed on travis especially when it's intermittent. Here more debug is being added to try and understand why a test is failing

* Log url on test failure
* Log page source on test failure
* Log stacktrace on assertion failure

### How to review 
1. Change an assertion/expectation to fail a selenium test.
1. Run the functional test
1. Check output of failing test

### CODE REVIEW

**Comment by samiwel** [comment]
With regards to the failing test, I found that it passes locally when `browser.isVisibleWithinViewport()` is used instead of `browser.isVisible()`.

**Comment by benjefferies** [comment]
As discussed, not to sure what the difference between the two are. I thought `isVisibleWithinViewport` was if the element is visible on the screen rather than in html. Looks like the implementation is slightly different which might make a difference. I suppose it wouldn't be wrong to use `isVisibleWithinViewport` as it should be visible onscreen. For this PR I think it's out of scope.

**Comment by collisdigital** [comment]
Can you paste a screenshot or .txt dump of what happens on failure?

**Comment by benjefferies** [comment]
Looks like

```
'Given I am completing an electronic questionnaire, when I have been inactive for X minutes, and my session will timeout in 3 minutes time, then I will be informed that my session is going to expire (in 2 minutes) and will be able to see how long I have until the session expires' failed. Dumping page source for url 'http://localhost:5000/questionnaire/test/timeout/UOX8EKF3JT/timeout-group/0/timeout-block'
<!DOCTYPE html><!--[if lt IE 7]>      <html lang="en-gb" dir="ltr" class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7"> <![endif]--><!--[if IE 7]>         <html lang="en-gb" dir="ltr" class="no-js lt-ie10 lt-ie9 lt-ie8"> <![endif]--><!--[if IE 8]>         <html lang="en-gb" dir="ltr" class="no-js lt-ie10 lt-ie9"> <![endif]--><!--[if IE 9]>         <html lang="en-gb" dir="ltr" class="no-js lt-ie10"> <![endif]--><!--[if gt IE 9]><!--><html xmlns="http://www.w3.org/1999/xhtml" lang="en-gb" dir="ltr" class="has-js"><!--<![endif]--><head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Survey</title>
    <meta content="" name="description" />
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <link rel="shortcut icon" href="/s/img/favicon.ico?q=99c4cc76ce66a155089008b33b3e9d61165965d1" />
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    <!--[if gt IE 8]><!-->
      <script async="" src="https://www.google-analytics.com/analytics.js"></script><script>document.documentElement.className = document.documentElement.className.replace('no-js','has-js')</script>
    <!--<![endif]-->
    
    
    <!--[if (gt IE 9) | (IEMobile)]><!-->
      <link href="/s/css/default/responsive.css?q=99c4cc76ce66a155089008b33b3e9d61165965d1" rel="stylesheet" />
    <!--<![endif]-->
    <!--[if (lte IE 9) & (!IEMobile)]>
      <link href="/s/css/default/fixed.css?q=99c4cc76ce66a155089008b33b3e9d61165965d1" rel="stylesheet">
    <![endif]-->
    <!-- Google Analytics -->
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', '', 'auto');
    ga('set', 'anonymizeIp', true);
    ga('send', 'pageview');
    </script>
    <!-- End Google Analytics -->
    <script>
      window.__EQ_SESSION_TIMEOUT__ = 6;
      window.__EQ_SESSION_TIMEOUT_PROMPT__ = 4;
      window.__EQ_SESSION_CONTINUE_URL__ = '/questionnaire/test/timeout/UOX8EKF3JT/timeout-continue';
      window.__EQ_SESSION_EXPIRED_URL__ = '/questionnaire/test/timeout/UOX8EKF3JT/session-expired';
    </script>
  </head>

  <body>

    

    <div class="page" aria-hidden="true">

      <div class="page__content">

        <div class="skip">
          <a class="skip__link" href="#main">Skip to content</a>
        </div>

        <header class="page__header">
          <div class="container">
  <div class="header">
    <div class="logo header__logo">
      
        <img src="/s/img/logo.svg?q=99c4cc76ce66a155089008b33b3e9d61165965d1" alt="Office for National Statistics" class="logo__img" />
      
    </div>
    <div class="info header__info" role="contentinfo">
      <h3 class="info__title venus" id="survey-help">Survey Help</h3>
      <div class="info__tel">
        <a class="info__link" href="tel:03001234931" aria-describedby="survey-help">0300 1234 931</a>
      </div>
      
      <dl class="info__list">
        <dt class="info__dt first"><abbr title="Survey identification code">ID:</abbr></dt>
        <dd class="info__dd">0</dd>
        <dt class="info__dt">Period:</dt>
        <dd class="info__dd">May 2016</dd>
        <dt class="info__dt"><abbr title="Reference number">Ref:</abbr></dt>
        <dd class="info__dd last">12346789012A</dd>
      </dl>
      
    </div>
  </div>
</div>
          <div class="bar " role="banner">
  <div class="bar__inner container">
    <div class="badge badge--amber u-mr-xs">BETA</div>
    
      <div class="bar__title venus">Timeout test</div>
    
  </div>
</div>
        </header>
        <div class="page__subheader">
          <div class="container">

            </div>
        </div>
        <div class="page__container container">
          

<div class="grid grid--reverse">
  <div class="grid__col col-4@m">
    
  

  </div>

  <div class="grid__col col-7@m pull-1@m">
    <main role="main" id="main" class="page__main">
      

    

    <form action="" class="form qa-questionnaire-form" role="form" method="POST" autocomplete="off" novalidate="">

      <div class="group" id="timeout-group">

        <div class="block" id="timeout-block">

        

          <section class="section" id="timeout-section">
  
    <h1 class="section__title saturn">
      Timeout</h1>
  
  

  
    
      
















<div class="question" id="timeout-question">

  

  

    

    

      <h2 class="question__title neptune">
      Timeout title
    </h2>
      

      

      
 <div class="question__answers">
      <div class="question__answer">
       



<div class="answer answer--textfield  " id="timeout-answer">

  
    
    <div class="answer__fields js-fields">
      
      

<div class="field">
    
    


<label id="label-timeout-answer" for="input-timeout-answer" class="label venus ">
  <div class="label__inner">
    Does the timeout appear?
    
  </div>
</label>


    
    
    

<input data-qa="input-text" class="input input--text " id="input-timeout-answer" value="" name="timeout-answer" />
</div>
    </div>
  
    
    
  
  
</div>
      </div>
     </div>


    

  
    

  

</div>
    
  
</section>

        

        </div>

      </div>

      <button class="btn btn--primary btn--lg qa-btn-submit venus" type="submit" name="action[save_continue]">Save and continue</button>
      <div class="u-mb-m">
        <button class="btn btn--link mars js-btn-save" type="submit" name="action[save_sign_out]">Save and complete later</button>
      </div>
    </form>


      
            
          
    </main>
  </div>
</div>


        </div>
      </div>

      <footer class="page__footer">
        
          <div class="footer page__footer" role="contentinfo">
  <div class="container">
    <div class="pluto">© <a class="footer__link" href="https://www.ons.gov.uk/" target="_blank">Office for National Statistics 2016</a></div>
  </div>
</div>
        
      </footer>

    </div>

    
      
        

<div class="dialog js-dialog" id="dialog">

  <div class="dialog__overlay" tabindex="-1"></div>

  <div class="dialog__body" role="dialog" aria-labelledby="dialog-title">
    <div role="document">

      <div class="mars u-mb-s">Timeout test</div>
      <h1 class="saturn dialog__title" id="dialog-title" tabindex="0">Your session is about to expire</h1>

      <div class="time js-timeout is-warning">

        <svg class="time__visual" width="80px" height="80px" viewBox="0 0 80 80" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
          <circle cx="40" cy="40" r="40" stroke="#D3D3D3" stroke-width="6" fill="none"/>
          <circle class="time__circle js-timeout-circle" cx="40" cy="40" r="40" transform="rotate(-90 40 40)" fill="none" stroke="red" stroke-width="6" stroke-linecap="round" style="stroke-dasharray: 61.6087, 1000;"/>
        </svg>

        <div class="time__text venus js-timeout-time">00:03</div>

      </div>

      <form class="" action="/" method="post">
        <button class="btn btn--primary btn--loader js-timeout-continue" type="button">Continue survey</button>
        <br />
        <button class="btn btn--secondary btn--border js-timeout-save" type="submit">Save and sign out</button>
      </form>
    </div>
  </div>
</div>
      
    

    <!--[if gte IE 9]><!-->
    
      <script src="/s/js/bundle.js?q=99c4cc76ce66a155089008b33b3e9d61165965d1" aria-hidden="true"></script>
    
        <!--<![endif]-->

    
</body></html>
------------------------------------------------------------------
[chrome 48.0 OS X 10.11 #0-0] Session ID: 496262ff-c435-4a7e-aeb7-f9a5c848515b
[chrome 48.0 OS X 10.11 #0-0] Spec: /Users/benjefferies/source/github/eq-survey-runner/tests/functional/spec/timeout.spec.js
[chrome 48.0 OS X 10.11 #0-0] Running: chrome (v48.0) on OS X 10.11
[chrome 48.0 OS X 10.11 #0-0]
[chrome 48.0 OS X 10.11 #0-0]   Session timeout
[chrome 48.0 OS X 10.11 #0-0]       1) Given I am completing an electronic questionnaire, when I have been inactive for X minutes, and my session will timeout in 3 minutes time, then I will be informed that my session is going to expire (in 2 minutes) and will be able to see how long I have until the session expires
[chrome 48.0 OS X 10.11 #0-0]       ✓ Given the timeout pop-up has appeared, when I choose to "Continue survey", then the pop-up will close and I am returned to the question I was last on with all data retained, and the timeout session resets to X minutes
[chrome 48.0 OS X 10.11 #0-0]       ✓ Given the timeout pop-up has appeared, when I choose to "Save and sign out", then I am redirected to a page confirming I have been signed out and that all data saved will be retained 
[chrome 48.0 OS X 10.11 #0-0]       ✓ Given the timeout pop-up has appeared, when I ignore it, then I will be signed out and redirected to a page confirming I have been signed out and that all data saved will be retained
[chrome 48.0 OS X 10.11 #0-0]
[chrome 48.0 OS X 10.11 #0-0]
[chrome 48.0 OS X 10.11 #0-0] 3 passing (25s)
[chrome 48.0 OS X 10.11 #0-0] 1 failing
[chrome 48.0 OS X 10.11 #0-0]
[chrome 48.0 OS X 10.11 #0-0] 1) Session timeout Given I am completing an electronic questionnaire, when I have been inactive for X minutes, and my session will timeout in 3 minutes time, then I will be informed that my session is going to expire (in 2 minutes) and will be able to see how long I have until the session expires:
[chrome 48.0 OS X 10.11 #0-0] expected true to be false
[chrome 48.0 OS X 10.11 #0-0] AssertionError: expected true to be false
[chrome 48.0 OS X 10.11 #0-0]     at Assertion.<anonymous> (/Users/benjefferies/source/github/eq-survey-runner/node_modules/chai/lib/chai/core/assertions.js:300:10)
[chrome 48.0 OS X 10.11 #0-0]     at Assertion.addProperty (/Users/benjefferies/source/github/eq-survey-runner/node_modules/chai/lib/chai/utils/addProperty.js:43:29)
[chrome 48.0 OS X 10.11 #0-0]     at Context.<anonymous> (/Users/benjefferies/source/github/eq-survey-runner/tests/functional/spec/timeout.spec.js:11:5)
```

**Comment by jonnyshaw89** [comment]
And the award :1st_place_medal: for the biggest PR comment goes to @benjefferies

**Comment by jonnyshaw89** [comment]
Im not sure how useful dumping the html to the log is?
isn't this just a worse implementation than the screenshots?

**Comment by benjefferies** [comment]
Being able to see the source or screenshot are both useful. At the moment we don't do anything with the screenshots they are taken then lost. We'd need to upload them to s3 or something to view them. I guess both are useful.

**Review by ajmaddaford — APPROVED** [review]

**Comment by collisdigital** [comment]
Since Travis uses PhantomJS a source dump is probably as good as it gets; guess you can always copy it to a HTML file and load in a browser

**Comment by benjefferies** [comment]
I wonder if we could do something with http://phantomjs.org/screen-capture.html on failure

**Comment by hamishtaplin** [comment]
@collisdigital I've noticed when running PhantomJS locally that it still generates screenshots.

**Comment by benjefferies** [comment]
You're right Hamish. Just been looking at it. I think it only captures screenshots on errors (elements not on page) rather than failures which might be enough for what we are looking at.

We'd still need somewhere to upload them to, S3?

**Review by samiwel — APPROVED** [review]

**Pull request merged**
