### PR TITLE
Final session hardening

### PR DESCRIPTION
**Pull request by warrenbailey**
### Changes
1. Generating a User IK along with the additional SALT required to generate the encryption key
2. The user ik is now stored in the cookie along side the session id
3. The user id remains in the database
4. The data in the database is now encrypted with a combination the user id, user ik and a PEPPER
5. Session and Session mapping table are now cleared on log in to prevent session fixation attacks
### How to test
1. Check out this branch
2. Enable Server side storage
3. Complete a survey, check everything still works
4. Check save and resume still works.
### Who can test

Anyone apart from @warrenbailey

---

This change is [Reviewable](https://reviewable.io/reviews/onsdigital/eq-survey-runner/249)

### CODE REVIEW

**Comment by collisdigital** [comment]
Need final IA approval before this is merged.

**Comment by warrenbailey** [comment]
Same goes for this PR then: https://github.com/ONSdigital/eq-terraform/pull/38 as that enables RDS

It would still be useful to get review comments now though and I can fix any issues while we wait for IA approval.

**Comment by dhilton** [comment]
IA approved - can we merge the other survey-runner PR's before this one so we can release a known good version before removing cookie storage.

**Comment by warrenbailey** [comment]
Rebased 🔢

**Comment by dhilton** [comment]
LGTM 👍

**Pull request merged**
