### PR TITLE
Remove numbering from Census

### PR DESCRIPTION
**Pull request by MIslam92**
### What is the context of this PR?
Removed section numbering & removed question numbering
As this does not provide user value and is incorrect when routed

### How to review 
- Run survey runner and run though all Census surveys to check that no numbers in questions/sections are displayed.

### CODE REVIEW

**Review by jcox-dev — CHANGES_REQUESTED** [review]
Couldn't see any numbering but is there a possibility for a test for this sort of thing? (As none were broken when these changes were introduced)

**Review by shahi645 — CHANGES_REQUESTED** [review]
Need to remove numbering from welsh versions.

**Comment by shahi645** [comment]
Also english version LGTM 👍🏿

**Comment by MIslam92** [comment]
@jcox-dev this should not be a problem as there was no tests previously testing the numbers on a page and if there was it would specifically check for the content on the page. Which would be to specific to a survey which should not be the case.

**Review by shahi645 — APPROVED** [review]
Welsh changes implemented on translate_schemas script

**Review by jcox-dev — APPROVED** [review]

**Pull request merged**
