### PR TITLE
Add beta bar

### PR DESCRIPTION
**Pull request by boxadesign**
### What is the context of this PR?

The new beta badge has been added. The beta badge is positioned next to the feedback accordion above the footer. See screenshot below for how it should look.

image

### How to review 
Check that it renders correctly.
Check different viewports.
Check the form still works correctly.

### CODE REVIEW

**Review by insacuri — APPROVED** [review]
👍 LGTM

**Review by bameyrick — APPROVED** [review]

**Review by MebinAbraham — COMMENTED** [review]
This will require additional static translation.

**Review by MebinAbraham — DISMISSED** [review]
@boxadesign 
If this is going in for LMS, we need to get the Welsh for:
`Give feedback and help us improve this service`
and get it added to the messages.po file.

**Comment by MebinAbraham** [comment]
@bameyrick @insacuri @boxadesign Can you make sure this is still working as expected.

**Review by bitdivision — APPROVED** [review]

**Pull request merged**
