### PR TITLE
eq-245 error pages

### PR DESCRIPTION
**Pull request by hamishtaplin**
screenshot 2016-04-08 16 09 49
### Changes
- added single error page template
### Test
- `npm run compile`
- recreate errors (404, etc) and check template displays as expected

### CODE REVIEW

**Comment by hamishtaplin** [comment]
This needs the browser/os version hooking up in the template. This does appear to be possible using a library: https://davidwalsh.name/user-agent-parser

**Comment by hamishtaplin** [comment]
NVM, I figure it out.

**Comment by hamishtaplin** [comment]
This is ready to go

**Comment by LJBabbage** [comment]
You have checked in your logs, can you remove them please

**Pull request merged**
