### PR TITLE
Changes to question wording on RSI/MCI for automotive fuel

### PR DESCRIPTION
**Pull request by shahi645**
### What is the context of this PR?
Forms 0205 and 0215 need wording changes to automotive sales questions

### How to review 
Launch SR and check form types 0205/0215 match changes listed on card: 
https://trello.com/c/Kmst6QyQ/1413-changes-to-question-wording-on-rsi-mci-automotive-fuel

### CODE REVIEW

**Review by yoganandkunche — CHANGES_REQUESTED** [review]
@shahi645 the newly added exclude item must be added on the preview page for both 0205 and 0215. 
@Donna Palmer  to update the spec

**Review by dwyeradam — APPROVED** [review]
LGTM

**Review by yoganandkunche — APPROVED** [review]

**Comment by yoganandkunche** [comment]
@shahi645 squishy squashy ?

**Comment by dwyeradam** [comment]
@shahi645 rebase please.

**Pull request merged**
