### PR TITLE
Routing in Household Accommodation section ENG/WLS/NIR

### PR DESCRIPTION
**Pull request by berroar**
### What is the context of this PR?
There was a routing issue in the household section for ENG/WLS and NIR. 

If there are no people (including visitors) in the household, then some questions need to be skipped.

For ENG/WLS, you should now be routed to the accommodation section summary from the central heating question if there are no people in the household.

For NI, you should now be routed to the accommodation section summary from the renewables question if there are no people in the household.

### How to review 
Check that the routing changes above have been implemented.

[ENG/WLS - Quick Launch](https://v3-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&case_type=HH&region_code=GB-ENG&url=https://gist.githubusercontent.com/berroar/8a6bf8383275bc0800105f934254b6c2/raw/d347ce410f04a3889146a3027a2f9e17cd3f1657/census_household_gb_eng.json)

[NI - Quick Launch](https://v3-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&case_type=HI&region_code=GB-NIR&url=https://gist.githubusercontent.com/petechd/bba13e090d6196203b829cfc3c425911/raw/3b836be7c7d747bd4a199384b50b5092db06b9d4/census_household_gb_nir.json)

### CODE REVIEW

**Comment by berroar** [comment]
[Routing in accommodation section based on list count of 0 (unoccupied property) is not currently applied (XS)](https://trello.com/c/dBrZJZjf/3247-routing-in-accommodation-section-based-on-list-count-of-0-unoccupied-property-is-not-currently-applied-xs)

**Comment by berroar** [comment]
[Routing in accommodation section based on list count of 0 (unoccupied property) is not currently applied (XS)](https://trello.com/c/dBrZJZjf/3247-routing-in-accommodation-section-based-on-list-count-of-0-unoccupied-property-is-not-currently-applied-xs)

**Review by ajmaddaford — CHANGES_REQUESTED** [review]
This has created an issue:

- Start a census household survey
- Don't add anyone to the household
- Complete the accommodation section
- Return to who lives here and add a householder
- Return to the hub

**Expected**: The accommodation section should be marked as incomplete.
**Actual**: The accommodation section remains complete. Clicking on the "View answers" link does nothing (it tries to redirect to the section summary, which is not on the routing path).

An interim fix could be to redirect to the first block if the section summary exists but isn't on the routing path. The full fix will require re-evaluating the completeness of the accommodation section if the list changes.

This issue will be affected by the card @LJBabbage is working on.

**Comment by ajmaddaford** [comment]
As agreed in the standup, we'll get this merged and raise a card for the edge case identified.

**Review by ajmaddaford — APPROVED** [review]

**Review by bitdivision — APPROVED** [review]

**Review by JamesGardiner — APPROVED** [review]

**Pull request merged**
