### PR TITLE
fixed IE bug with survey header info width

### LINKED ISSUE #1023: IE: ru_ref display issue when we have a lengthy Period
### Expected behaviour
Must display the full ru_ref even when the period is lengthy

### Actual behaviour
in IE 11 ru_ref is only partially displayed when we have a lengthy period Eg: 01 February 2017 (PFA)

Work fine in Chrome as it is clever enough.!
### Steps to reproduce the behaviour
Launch any survey RSI/MCI/MWSS/QBS which has a lengthy period (Ex: 01 February 2017)
On the landing page 

#### Browser
IE 11
### Screenshot
screen shot 2017-03-08 at 11 49 52

### PR DESCRIPTION
**Pull request by hamishtaplin**
### What is the context of this PR?

Fixes #1023. 

### How to review 

As per bug reproduction steps.

### CODE REVIEW

**Review by LJBabbage — APPROVED** [review]

**Comment by collisdigital** [comment]
@hamishtaplin can you rebase and fix the tests?

**Comment by hamishtaplin** [comment]
@collisdigital tests were failing randomly, all works now :)

**Comment by collisdigital** [comment]
Would be good to see this tomorrow running in various IE version to ✅ it off; can we do in the morning?

**Comment by benjefferies** [comment]
Maybe it would be good to sanity check with various IE browsers through browserstack

**Review by ajmaddaford — APPROVED** [review]
Tested on BrowserStack

**Pull request merged**
