### PR TITLE
Removing space in survey id

### PR DESCRIPTION
**Pull request by warrenbailey**
### What is the context of this PR?
Removing the space in survey id as it causes SDX to fail validation

### How to review 
Launch and complete an LMS survey

### CODE REVIEW

**Review by nealedj — CHANGES_REQUESTED** [review]
Ah nice.

All good but could you remove the new line at the end of the file please?

**Review by shahi645 — APPROVED** [review]
Just to run a yarn format

**Comment by ajmaddaford** [comment]
@warrenbailey validation should be added to https://github.com/ONSdigital/eq-schema-validator/blob/master/schemas/questionnaire_v1.json for this - either to restrict to a set of characters or to not allow spaces.

**Review by davecharles — APPROVED** [review]
LGTM

**Review by nealedj — APPROVED** [review]

**Comment by nealedj** [comment]
@ajmaddaford I'll add a card to validate this

**Pull request merged**
