### PR TITLE
Remove 'volunteering' question from census_household

### PR DESCRIPTION
**Pull request by shahi645**
### What is the context of this PR?
- volunteering question removed
- functional/integration tests updated to reflect change
- only applied to `census_household` not `census_individual`

### How to review 
Run SR and open `census_household` survey and check `volunteering` question no longer remains. Run unit/integration tests and make sure they pass.
Run `yarn test_functional --spec=census-household` to test the functional tests still pass

### CODE REVIEW

**Review by MIslam92 — DISMISSED** [review]
Format 🙃

**Comment by jonnyshaw89** [comment]
@shahi645 How about census_individual?

**Comment by shahi645** [comment]
@jonnyshaw89 spoke to Donna about this and only needed for household as thats the one being tested, so not to bother with individual

**Review by jonnyshaw89 — APPROVED** [review]

**Review by MIslam92 — APPROVED** [review]

**Comment by MIslam92** [comment]
@shahi645 "Squishy squashy"

**Pull request merged**
