### PR TITLE
3122 save and complete later s

### PR DESCRIPTION
**Pull request by petechd**
### What is the context of this PR?
This removes the hidden button element and changes button to link tag by providing "url" parameter to Design System's Header component.

### How to review
Use ChromeDev Tools or similar to investigate the changes and make sure that hidden button has been removed and the "Save and Sign Out" button is now a link.  [Trello card](https://trello.com/c/KFIrxgKL/3122-save-and-complete-later-s)

### CODE REVIEW

**Comment by petechd** [comment]
[Save and complete later (S)](https://trello.com/c/KFIrxgKL/3122-save-and-complete-later-s)

**Comment by JamesGardiner** [comment]
LGTM - needs v3 merged in though

**Comment by JamesGardiner** [comment]
Might want to get @rmccar to take a look as well

**Comment by rmccar** [comment]
LGTM

**Review by JamesGardiner — APPROVED** [review]

**Review by rmccar — APPROVED** [review]

**Pull request merged**
