### PR TITLE
Added happy path UKIS selenium test

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
Have added a Happy path test that submits the UKIS survey

### How to review 
Does the test work?

### CODE REVIEW

**Review by benjefferies — APPROVED** [review]

**Review by LJBabbage — CHANGES_REQUESTED** [review]
Bad indenting (none) Surprised Ben has approved, he loves his indenting

**Comment by jonnyshaw89** [comment]
@LJBabbage can you point out the bad indentation?

**Comment by LJBabbage** [comment]
We usually only put one command on each line, so
```
ExpenditureInternalInvestmentRD.setExpenditureInternalInvestmentRDAnswer(1703000).submit()
```
**becomes** 
```
ExpenditureInternalInvestmentRD.setExpenditureInternalInvestmentRDAnswer(1703000)
                               .submit()
```

**Comment by jonnyshaw89** [comment]
@LJBabbage not in any of the Census or MWSS ones we haven't

**Review by LJBabbage — APPROVED** [review]

**Pull request merged**
