### PR TITLE
Fixes #193 minimise js cachebusting

### LINKED ISSUE #193: Minified assets/cachebusting
### Expected behaviour
- production environment should serve minifed assets (js/css)
- production environment should employ cache-busting techniques
### Actual behaviour
- production environment is serving non-minified assets
- production environment does not employ cache-busting techniques
### Steps to reproduce the behaviour
- visit survey on production environment
- confirm css and js files do not have .min in the filenames
- confirm no cache-busting employed
### Technical information

All browsers/OS

### PR DESCRIPTION
**Pull request by warrenbailey**
### Changes

Fixes #193 - version static assets and serve minimised js and css in production.
### How to test
1. Check out this branch
2. Run the application and check that all static assets are requested with a version (e.g. q=acd4cf308362322b93819e5ffdb961125089e65a)
3. Check minimised assets are being served
4. Set the env variable EQ_MINIMIZE_ASSETS to True
5. Check minimised assets are being served
### Who can test

Anyone apart from @warrenbailey

### CODE REVIEW

**Comment by dhilton** [comment]
@hamishtaplin @warrenbailey Should this be applied to all assets? I.e. favicon & svg files? Looking at the web server logs for this PR not all elements have the cache busting applied. Is that ok?

e.g. 

```
[2016-05-13 10:55:03,895] INFO [werkzeug._log:87] 127.0.0.1 - - [13/May/2016 10:55:03] "GET /s/img/icons/icons--phone.svg HTTP/1.1" 200 -
[2016-05-13 10:55:03,899] INFO [werkzeug._log:87] 127.0.0.1 - - [13/May/2016 10:55:03] "GET /s/img/icons/icons--info-circle.svg HTTP/1.1" 200 -
```

**Comment by hamishtaplin** [comment]
@dhilton @warrenbailey I can optimise svgs but it would be a separate process. The cache-busting thing is up for debate, they are unlikely to change so it's probably not worth the effort.

**Comment by warrenbailey** [comment]
@dhilton anything using url_for should get the version information. I'll have a look at why the favicon and svg aren't.

**Comment by warrenbailey** [comment]
It does version svg but only if they go through url_for().

2016-05-13 11:16:58,768] INFO [werkzeug._log:87] 127.0.0.1 - - [13/May/2016 11:16:58] "GET /s/img/logo.svg?q=b462c0fd4b8a1130cae2a7ffd62fbc050cdf9cfc HTTP/1.1" 200 -

The icons--info-circle.svg and icons--phone.svg are referenced from the css file, nothing I can do about those, so Hamish would need to change the css files if we want them versioned.

**Comment by dhilton** [comment]
Ok - LGTM.

**Pull request merged**
