### PR TITLE
Update self-contained household question

### PR DESCRIPTION
**Pull request by MIslam92**
### What is the context of this PR?
Census household changes:
- pipe in address line one into question

Card: https://trello.com/c/Mp0aNgGb/1465-update-is-accommodation-self-contained

### How to review 
Run Survey Runner and check that in Census Household questionnaire the address line one is passed in the self-contained accommodation question

### CODE REVIEW

**Review by dwyeradam — APPROVED** [review]

**Comment by shahi645** [comment]
@MIslam92 @charlotte-hirst in the design the guidance has no box around it, is that just an accident or is the guidance not meant to have a box around it?

**Comment by charlotte-hirst** [comment]
only use the boxes for include and exclude lists

**Review by charlotte-hirst — DISMISSED** [review]
LGTM when the guidance is moved out of the box

**Review by shahi645 — APPROVED** [review]
@MIslam92 Squishy-squashy

**Comment by MIslam92** [comment]
@charlotte-hirst can you have a quick look whenever ur free so I can get this merged or remove ur review as its blocking me from merging this

**Pull request merged**
