### PR TITLE
Fixes to ensure we skip the totaliser with only one answer

### PR DESCRIPTION
**Pull request by bitdivision**
### What is the context of this PR?
[trello](https://trello.com/c/aUmijOwt/2494-issue-totaliser-showing-when-only-1-value)

Two situations were broken (wrt skipping the totaliser when there is only 1 value):
1) One job / working this week / no overtime / Usual Hours no answer
    - Should skip the totaliser and go to: `Why fewer hours than usual`.
2) Casual worker
    - If appropriate, skip the totaliser

Here is my logic for casual working:

```
If overtime == 4 (No overtime):
    if CASAC == 0:
        if self-employed:
            Goto YLESS.SEMP
        else
            Goto YLESS.EMP
    else:
        if self-employed:
            Goto CONM.SEMP
        else
            Goto CONM.EMP
```

I have confirmed that they do want the user to be routed to YLESS when usual hours is not set.

The slides also state that on casual actual hours, they should be routed to YLESS if CASAC is 0 or unset.

### How to review 
Check that the situations above skip the totaliser if there would be only one value.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Review by MebinAbraham — COMMENTED** [review]
Not directly related but you asked for it:
`Unpaid overtime` when `Casual` asks `Usual` hours but it shouldn't.

**Review by MebinAbraham — COMMENTED** [review]
- Working (Non-casual, 1 job)
- No overtime
- Set `Usual hours`, don't set `Actual hours` or `0`

Returns totaliser with 1 value.

**Comment by bitdivision** [comment]
> Unpaid overtime when Casual asks Usual hours but it shouldn't.

Fixed (was lower case `unpaid overtime`)

**Comment by MebinAbraham** [comment]
Other scenarios seem to work as expected 👍 so just need the above fixed.

**Comment by bitdivision** [comment]
> Working (Non-casual, 1 job)
> No overtime
> Set Usual hours, don't set Actual hours or 0
> Returns totaliser with 1 value.

I've simplified the routing on actual-hours-confirmation quite drastically. 

```
if confirmation-answer == No:
    goto actual-hours-question
elif casual worker:
    goto when-did-you-start-working
elif 'No overtime':
    goto why-did-you-work-fewer-hours-than-usual (two versions depending on employment)
else:
    goto totaliser
```

**Comment by bitdivision** [comment]
Closing for now. Not strictly necessary for LMS release.

**Pull request closed without merging**
