### PR TITLE
eq-533 Thankyou Page Improvements

### PR DESCRIPTION
**Pull request by hamishtaplin**
### What is the context of this PR?

[Trello card](https://trello.com/c/MNFZTnns/533-0-5-thank-you-page-improvements)

Accessibility testing feedback indicated that the copy on this page was confusing to screen-readers. This PR implements their feedback.

Furthermore, I've refactored how the `alert` component works—removing the include as it was cumbersome to implement. I've implemented the new `alert` style on the thank-you and error pages, replacing the `box` component that was used previously.
### How to review
1. `npm run compile` 
2. Visit any survey and invoke errors, checking they still look like the screenshot below:

screenshot 2016-09-15 16 20 11
1. Successfully complete a survey, the thankyou page should look like this:

screenshot 2016-09-15 16 23 06
1. Visit an error page:

screenshot 2016-09-15 16 19 47
- [ ] Do all commits have sensible commit messages?
- [ ] Is all new code unit tested?
- [ ] Are there integration tests if needed?
- [ ] Is there sufficient logging?
- [ ] Is there documentation or is the code self-describing?
### Who worked on the PR

@hamishtaplin.

### CODE REVIEW

**Review by collisdigital — COMMENTED** [review]
@hamishtaplin can you also paste a screenshot of the error screen with a transaction id (e.g. launch a questionnaire and navigate to an invalid URL)?

**Comment by hamishtaplin** [comment]
This will definitely need the commits squashing, whomever merges it.

**Comment by hamishtaplin** [comment]
@collisdigital

screenshot 2016-09-15 16 35 05

**Comment by collisdigital** [comment]
As a general point (not related to this story), I wonder if "Please call the number above" is appropriate for screen reader users.

**Comment by hamishtaplin** [comment]
@collisdigital Agreed. We could just put the number in that bit of copy or even add it afterwards but hidden to non-screenreader users.

**Comment by bennpearson** [comment]
LGTM 👍

**Pull request merged**
