### PR TITLE
Update Retail Sales guidance wording

### PR DESCRIPTION
**Pull request by dwyeradam**
### What is the context of this PR?
Requested content changes for Retail sales exclude guidance.

### CODE REVIEW

**Review by charlotte-hirst — APPROVED** [review]

**Comment by charlotte-hirst** [comment]
sorry adam they want to change 2 more things ill add them in now - sorry

**Comment by charlotte-hirst** [comment]
Of the £20.00 retail sales, how much were your online sales?  delete 'including VAT' from question and intro. Highlight 'online sales' instead please

**Comment by charlotte-hirst** [comment]
change this line: Data should relate to all sites in England, Scotland, Wales and Northern Ireland, but excludes the Channel Islands and Isle of Man.
To "The UK consists of England, Scotland Wales and Northern Ireland, but excludes the Channel Islands and the Isle of Man"

**Review by charlotte-hirst — COMMENTED** [review]
LGTM

**Review by nealedj — APPROVED** [review]

**Pull request merged**
