### PR TITLE
Replace Census Household Schema

### PR DESCRIPTION
**Pull request by MebinAbraham**
### What is the context of this PR?
Changes to `census_household.json`
[Trello](https://trello.com/c/y63uPoPj/2595-replace-census-schema)

### How to review 
- Have I copied and pasted correctly and yarn formatted?
- I have also modified existing tests which broke since they were referencing the old `test_census_household` schema.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Comment by MebinAbraham** [comment]
Need some changes. Doesn't pass validator and routing can be reduced.

**Comment by MebinAbraham** [comment]
I have removed some of the redundant routings. Ensure that the changes are equivalent.

There are also routing rules that can be done as skip conditions instead but I have not done this for the time being.

**Comment by MebinAbraham** [comment]
Updated unit and functional tests that referenced the old census schema.

**Review by dwyeradam — APPROVED** [review]
I've reviewed the changes to the tests and you haven't weakened them so good enough for me. Charlotte said `census_household.json` does not need additional review by devs and can be accepted based on her review.

**Review by charlotte-hirst — APPROVED** [review]

**Comment by bitdivision** [comment]
Cool, I'll merge this then, though I haven't reviewed properly.

**Pull request merged**
