### PR TITLE
Issue 602 census country of birth bug

### PR DESCRIPTION
**Pull request by yoganandkunche**
### What is the context of this PR?
Creating new folder structure for census related selenium test 

### How to review 

yarn run test_functional -- --spec=census/issues/fulltime-education-question
yarn run test_functional -- --spec=census/issues/arrive-in-uk-question

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
These tests are running on the build? is that intentional? cc. @benjefferies

**Comment by benjefferies** [comment]
Not intentional but no harm in them running at the moment I guess?

**Comment by jonnyshaw89** [comment]
If we get this PR in then rebase they should start passing.
https://github.com/ONSdigital/eq-survey-runner/pull/608

**Comment by jonnyshaw89** [comment]
Merged into https://github.com/ONSdigital/eq-survey-runner/pull/608

**Pull request closed without merging**
