### PR TITLE
Remove support for SQL database

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
We are currently making a query on questionnaire state before writing changes.
This is done to support SQL database where we need to know if we are performing an INSERT or an UPDATE.
We no longer need to do this if we don't want to support SQL databases any more as the NoSQL databases that we are using don't need us to specify if we are inserting or updating.

This PR removes that check.

### How to review 
Does the saving of questionnaire state work as expected?

### CODE REVIEW

**Comment by bitdivision** [comment]
If we're breaking support for SQL databases here, shouldn't this PR be removing all SQL database references?

**Comment by jonnyshaw89** [comment]
@bitdivision If we decide that this is an approach we want to take then yeh I can do that.

**Comment by nealedj** [comment]
Or do it on a feature flag? I implemented the same thing before - I thought I'd discussed it with you but it must have got lost in the other changes: https://github.com/ONSdigital/census-survey-runner/pull/11

Rationale for closing it in a feature flag was because for business there was a greater chance of two users interacting with the same questionnaire at the same time.

**Comment by jonnyshaw89** [comment]
@nealedj Im not sure that this would have had much impact saving data when two users were interacting as it blatted over the data after it read anyway.

https://github.com/ONSdigital/eq-survey-runner/pull/2047/files#diff-91332e4f9b1ffb424d8ceb2168bc05aeL27

**Comment by bitdivision** [comment]
I think this is the right approach. Continuing to support SQL databases is very prone to error if we're not actively using it in any projects. It shouldn't be hard to add back in if someone really needs it.

**Review by bitdivision — APPROVED** [review]
🎉

**Review by ajmaddaford — CHANGES_REQUESTED** [review]
- The removal of elastic beanstalk related files should be in another pull request
- There are still some references to the database:
  - app/secrets.py
  - docker-secrets.yml
  - scripts/generate_secrets.py

**Review by ajmaddaford — COMMENTED** [review]
Minor quibble, the commit message should be capitalised - "remove" -> "Remove"

**Review by ajmaddaford — APPROVED** [review]

**Comment by bitdivision** [comment]
You forgot to setup GPG @jonnyshaw89

**Review by ajmaddaford — CHANGES_REQUESTED** [review]
The `database-scripts` folder needs to be deleted

**Review by MebinAbraham — APPROVED** [review]

**Review by ajmaddaford — APPROVED** [review]

**Pull request merged**
