### PR TITLE
Update root view

### PR DESCRIPTION
**Pull request by weapdiv-david**
**_What**_

Updates the view returned by the root url, to remove the Hello World message, and replace it with a link to the ONS home page.

**_How to test**_

1) Checkout the branch
2) Run the app
3) Visit [home page](http://localhost:5000/) and verify the "Hello World" message has been replaced.

**_Who can test**_

Anybody except @weapdiv-david

### CODE REVIEW

**Comment by collisdigital** [comment]
I think this page should be our generic error page. No one should access eQ via the root page, that is an invalid action. We have error page on our backlog for this Sprint....

**Comment by collisdigital** [comment]
This can be researched as part of the error page stuff in future. This was the story in this Sprint: https://trello.com/c/iLfxqu3u

**Comment by weapdiv-david** [comment]
This has arisen out of a conversation with Steve, but I agree it needs to be researched further.  With regard to using an error page though, the elasticbeanstalk deployment seems to check the status of the root url before signalling whether a deployment was successful or not.  Treating the access of the root url as an erro may cause more problems than it solves.

**Comment by collisdigital** [comment]
Yeah maybe return 200 code but same page?

**Comment by warrenbailey** [comment]
So to clarify, we're going to display the error page but return a 200?

**Comment by collisdigital** [comment]
That's what I would suggest; if we agree this is an error condition (hitting eQ directly); my expectation it's the same as going to any URL without a valid token

**Comment by warrenbailey** [comment]
Error pages are now in place, so we should be able to progress this now.

**Comment by warrenbailey** [comment]
Displaying an error page with a 200 code (needed for Elastic beanstalk)

**Comment by warrenbailey** [comment]
Ready for review

**Pull request merged**
