### PR TITLE
Upgrade pylint to 1.7.4

### PR DESCRIPTION
**Pull request by jcox-dev**
New version of pylint was picked up by Pipenv in #1301. This PR is for fixing all the new issues.

### CODE REVIEW

**Review by shahi645 — APPROVED** [review]
We should reduce the number of times we disable py-lint, but all py-lint checks pass with upgraded version 👍🏿

**Review by ajmaddaford — APPROVED** [review]

**Comment by jcox-dev** [comment]
@ajmaddaford @shahi645 adding some changes that removes the need for a few of the disable comments.

**Comment by jcox-dev** [comment]
This might now need to be updated to use Pipfile for dependencies now that #1301 has been merged.

**Comment by jcox-dev** [comment]
This is now using the Pipfile and Pipefile.lock to define dependencies.

**Comment by jcox-dev** [comment]
@ajmaddaford @shahi645 couple of new changes since approval that might need a once over.

**Comment by shahi645** [comment]
New changes make sense, can you squash please @jcox-dev

**Pull request merged**
