### PR TITLE
EQ-399 Refactor MetaDataStore to use self describing items

### PR DESCRIPTION
**Pull request by warrenbailey**
### What is the context of this PR?

Refactoring MetaDataStore to use self describing items as discussed here: https://digitaleq.atlassian.net/wiki/display/EQ/Smelly+Code
### How to review
1. Complete a survey and check no functionality is broken 
- [x] Do all commits have sensible commit messages?
- [x] Is all new code unit tested?
- [x] Are there integration tests if needed?
- [x] Is there sufficient logging?
- [x] Is there documentation or is the code self-describing?
### Who worked on the PR

@warrenbailey

### CODE REVIEW

**Comment by warrenbailey** [comment]
Ready for review :)

**Comment by LJBabbage** [comment]
I get errors when using the dev page :-1:
[2016-07-05 09:07:51,720] WARNING [app.authentication.session_management.clear:107] No eq session id exists
[2016-07-05 09:07:51,723] ERROR [app.metadata.metadata_store.is_valid:56] COLLECTION_EXERCISE_SID
[2016-07-05 09:07:51,723] ERROR [app.metadata.metadata_store.is_valid:56] EMPLOYMENT_DATE
[2016-07-05 09:07:51,723] ERROR [app.metadata.metadata_store.is_valid:56] EQ_ID
etc

**Comment by warrenbailey** [comment]
Apologies missed the dev pages, will fix that now

**Comment by LJBabbage** [comment]
:thumbsup:

**Pull request merged**
