### PR TITLE
Schema only changes for LMS who lives here

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
Duplicate who lives here for the no primary flow
Corrected routing rules

### How to review 
Does it work as per slides?

### CODE REVIEW

**Comment by insacuri** [comment]
screenshot 2018-10-16 at 11 45 57

Just got into this state by adding 2 people and 1 student.  Not sure where the highlighted 'Person' is coming from

**Comment by jonnyshaw89** [comment]
@insacuri probably here https://github.com/ONSdigital/eq-survey-runner/pull/1832/files#diff-c9e6b1b5985ae51160d65d915d321a01R685

**Comment by jonnyshaw89** [comment]
@insacuri Relationship title has been fixed

**Review by insacuri — APPROVED** [review]
LGTM 👍

**Review by dcdarrell9 — APPROVED** [review]
Other issues regarding answer_store / navigation etc to be done with another card

**Comment by bitdivision** [comment]
squashy

**Pull request merged**
