### PR TITLE
Read schema files as UTF-8

### PR DESCRIPTION
**Pull request by warrenbailey**
**What**
Read the schema file as UTF-8, needed for the £ sign that is now in it.

**How to test**
1. Start the server
2. Browse to http://localhost:5000/questionnaire/1
3. Check the survey is rendered correctly

**Who can review**
Anyone apart from @warrenbailey

### CODE REVIEW

**Comment by dhilton** [comment]
This works for me - just awaiting ElasticBeanstalk test to make sure that it works in our deployment environment.

**Comment by warrenbailey** [comment]
Tested and it works on Elastic Beanstalk

http://warren-surveys.eq.ons.digital/questionnaire/1

**Comment by weapdiv-david** [comment]
Have rebased against master.  LGTM :+1:

**Comment by dhilton** [comment]
Happy after conversation :+1:

**Pull request merged**
