### PR TITLE
Use python package for translations

### PR DESCRIPTION
**Pull request by bitdivision**
### What is the context of this PR?
This removes the requirement for using docker for running translations. It updates the dockerfile to use the build.sh script and adds the python package for eq_translations.

It also removes the docker part of template extraction and replaces it with a call to the python package.

Should be reviewed in tandem with https://github.com/ONSdigital/eq-translations/pull/38

### How to review 
Test that translations work correctly, both outside and inside of docker.

Easiest way to do this is to call the scripts manually, and to run the docker-compose build process, which will call build.sh and build all the schemas.

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Review by JamesGardiner — DISMISSED** [review]

**Review by JamesGardiner — COMMENTED** [review]
Having issues running the translations from docker

**Comment by iwootten** [comment]
Is it worth updating the template extraction script to use the package in the same way, so we don't use docker from scripts at all?

**Comment by bitdivision** [comment]
@iwootten - Yes absolutely. I'll do that now.

@JamesGardiner Any details?

**Comment by bitdivision** [comment]
Template extraction now handled through the package @iwootten .

I've also had to pin redis to an older version, it looks like there is some churn in that package, which is causing our tests to fail. Hopefully that will settle down soon.

**Review by JamesGardiner — APPROVED** [review]
Approving based on the translations working as specified here however, there are issues when trying to run the commands from inside a docker container on some systems (failed on Manjaro Linux). This won't be an issue as we don't intend to use the scripts this way.

**Comment by bitdivision** [comment]
@JamesGardiner Cheers. 

As discussed, I'm not going to worry too much about the scripts not working when run through the runtime docker containers. The scripts should really only ever be run during the build of the container (first stage). If we want to provide a docker environment for running scripts then we could do that based off the first stage, but I don't think there's a real need for that at the moment.

**Review by ajmaddaford — APPROVED** [review]

**Review by MebinAbraham — CHANGES_REQUESTED** [review]
Am I missing something obvious?

```
ImportError: cannot import name 'extract_template' from 'eq_translations.entrypoints' (/Users/abrahm/.local/share/virtualenvs/eq-survey-runner-7OUsly8u/src/eq-translations/eq_translations/entrypoints.py)
make: *** [translation-templates] Error 1
```

**Review by MebinAbraham — APPROVED** [review]

**Pull request merged**
