### PR TITLE
bug fixs for 1_888.json

### PR DESCRIPTION
**Pull request by LJBabbage**
### Changes

Wording changes for 1_888.json
### How to test

Make sure the questionnaire works
### Who can test

Anyone but @LJBabbage

### CODE REVIEW

**Comment by hamishtaplin** [comment]
If you reference the bug, it'll close it when this gets merged.

**Comment by warrenbailey** [comment]
@hamishtaplin does this actually have an issue related to it?

**Comment by warrenbailey** [comment]
rebasing

**Comment by hamishtaplin** [comment]
@warrenbailey I dunno. Maybe not then.

**Comment by warrenbailey** [comment]
I think it's comments made by Richie. Lewis just named the PR badly

**Comment by warrenbailey** [comment]
LGTM 👍

**Pull request merged**
