### PR TITLE
Add headless functional testing option using phantomjs

### PR DESCRIPTION
**Pull request by ajmaddaford**
### What is the context of this PR?
Using phantomJS as the browser for running selenium tests. This decreases test execution time.

### How to review
1. yarn compile to install new dependencies
1. run selenium tests locally to ensure via `yarn test_functional_headless `

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
Build times are looking a lot more reasonable now!

**Review by benjefferies — APPROVED** [review]

**Review by jonnyshaw89 — APPROVED** [review]

**Comment by benjefferies** [comment]
Rebase, squash, rebase, merge?

**Review by hamishtaplin — CHANGES_REQUESTED** [review]
this needs the config to not be duplicated, I'll sort it

**Review by hamishtaplin — APPROVED** [review]

**Comment by ajmaddaford** [comment]
This is failing on the timeout tests as they are dependent on session storage (which isn't supported by phantomjs). The phantomjs tests have been reworked so they no longer rely on session storage in #970

**Pull request merged**
