### PR TITLE
Update sinon, mocha and livereload dependencies

### LINKED ISSUE #1132: Review project dependencies in light of BitHound analysis.
### Description
The [BitHound Analysis for survey runner](https://www.bithound.io/github/ONSdigital/eq-survey-runner/https://www.bithound.io/github/ONSdigital/eq-survey-runner/) has highlighted a number of out-of-date packages being used in survey runner.
A few of these packages are considered insecure and have security advisories against them.
Others are listed as risky upgrades since the versions have fallen behind quite a bit.
Granted some of these are dev dependencies, and not application dependencies. But probably still worth reviewing at some point.

I've created this task so that the front end dependencies can be reviewed and a decision taken as to whether we:
a) Leave the versions as-is accepting the risks and potentially more difficult migrations in the future,
b) Upgrade the dependency versions to newer releases, or
c) use a different dependency.

### Screenshot
image

### PR DESCRIPTION
**Pull request by nealedj**
### What is the context of this PR?
Fixes #1132.

Updates versions of mocha and sinon to newer versions.

Updates gulp-livereload to gulp-refresh. Refresh is a fork of livereload which is actively maintained. Livereload is now considered unmaintained.

Adds a new feature flag to enable livereload. When this flag is enabled the CSP policy is altered to allow livereloading and the browsersync script is added to the base template.

### How to review 
All functional tests should pass

To test live reloading:
- Run the app locally
- Also run `yarn start`
- Start a questionnaire
- A message should say "Browsersync: connected"
- Make a change to a JS, SCSS or HTML file
- The browser should refresh and reflect the change

### CODE REVIEW

**Comment by shahi645** [comment]
@nealedj while we are here updating versions of packages, should we update our selenium driver version in the `chimp.js` folder to `2.37`?

**Comment by nealedj** [comment]
@shahi645 I tried that but the functional tests fail on travis on the newer version.

**Comment by shahi645** [comment]
@nealedj For travis we'd have to update the chrome version too, but i thought they were both pinned in the travis config anyways

**Comment by nealedj** [comment]
@shahi645  Ah okay. Let's keep that separate anyway. Beyond the scope of this job.

**Comment by shahi645** [comment]
@nealedj trying to refresh browser, cmd line says its refreshing, but actual browser page doesn't reload 😕

**Comment by MebinAbraham** [comment]
@nealedj Same thing as @shahi645

**Review by MebinAbraham — COMMENTED** [review]
@nealedj Getting same behaviour @shahi645 mentioned.

cmd says `Reloading Browsers` when making HTML and JS changes but only detects thats files have changed when modifying CSS.

**Review by MebinAbraham — COMMENTED** [review]
I get this in the console?
`:5050/browser-sync/browser-sync-client.js?v=2.24.4:1 `
`Failed to load resource: net::ERR_EMPTY_RESPONSE`

**Comment by MebinAbraham** [comment]
@shahi645 Its a port conflict.

**Comment by shahi645** [comment]
weird, i didn't have docker running so that port should have been clear

**Comment by MebinAbraham** [comment]
@shahi645 Must be something else for you. Fixing port, fixed the issue for me.
If running in PyCharm, make sure the env is set, and worth checking console log.

**Comment by nealedj** [comment]
@MebinAbraham are you able to suggest a port that doesn't conflict with any of the RAS services you were running?

**Review by shahi645 — APPROVED** [review]
Tested and verified 👍

**Comment by MebinAbraham** [comment]
@nealedj I don't know what the convention regarding ports is but 5075 is free and most around it.
Happy to approve once port issue has been resolved.

**Comment by nealedj** [comment]
It's sensible to try and avoid [well-known ports](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers) but since that's neither complete nor static it's always a bit of a guess.

Browsersync is using dynamic ports but we're referencing the script it hosts using a static port. I can't think of any easy way to dynamically hook up the script.

Let's try 5075.

**Review by MebinAbraham — APPROVED** [review]
Working as expected. 👍 
Browsersync on port 5075 and UI on 5076

Squishy Squashy!

FYI: It's secure messaging that was running on 5050

**Pull request merged**
