### PR TITLE
Update ISSUE_TEMPLATE.md to include IE11 and Screenshot

### PR DESCRIPTION
**Pull request by collisdigital**
### Changes

Add IE11 to browsers and Screenshot heading for screenshots
### How to test

Assume you have to merge this in order to test it? But raise a new issue and see the changes applied to the template.
### Who can test

Anyone but @collisdigital

### CODE REVIEW

**Comment by weapdiv-david** [comment]
So what's the longest a pull request has been on the board so far?

**Comment by collisdigital** [comment]
@weapdiv-david Not sure but I get this message below yours that says "As an administrator, you may still merge this pull request." hmmm...

**Comment by warrenbailey** [comment]
Needs rebasing rather than merge but LGTM 👍

**Comment by warrenbailey** [comment]
LGTM 👍

**Pull request merged**
