### PR TITLE
Fix error when resuming a survey

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
When an answered answer has been removed from the schema, the upgrade now skips that answer as it cannot find it.

Fixes https://github.com/ONSdigital/eq-survey-runner/issues/1403

### CODE REVIEW

**Review by shahi645 — APPROVED** [review]
Tested and verified this works, test also passes

**Review by yoganandkunche — CHANGES_REQUESTED** [review]
@jonnyshaw89 as discussed it fails with error 500 when the whole block is removed. Work when only the answer is removed.

**Comment by shahi645** [comment]
@yoganandkunche I think thats what the issue is related to. Only when an answer is removed

**Comment by yoganandkunche** [comment]
@shahi645 Yes the issue is only related to answer but it should also cater for the block removal, when we get a request from business comes to remove the whole question.

**Review by yoganandkunche — APPROVED** [review]
@jonnyshaw89 squishy-squashy?

**Pull request merged**
