### PR TITLE
Change submit button text on interstitial page

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
Fixes https://github.com/ONSdigital/eq-survey-runner/issues/1743

### CODE REVIEW

**Comment by insacuri** [comment]
Which surveys have interstitial pages?  Just wanna quickly test this before I approve it

**Comment by jonnyshaw89** [comment]
@insacuri any with a block type of `"type": "Interstitial"`

**Review by bitdivision — APPROVED** [review]
Tested :+1:

**Review by insacuri — APPROVED** [review]
LGTM

**Pull request merged**
