### PR TITLE
MBS 0111 Variant

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
Added the Blocks and Manifest to build mbs_0111

### How to review 
Run it and review if it matches the Google Slides.
https://docs.google.com/presentation/d/1yoo1dFRqe4XeBArDqIY_vg5G6LeDt_6W7iyW60Aj2Fg

### CODE REVIEW

**Comment by charlotte-hirst** [comment]
Noticed code refers to mci and RSI but its for MBS
Title in heading - lose RSI
Reporting period 
- can we get the date to stay together on 1 line, as currently wraps after day and the rest of date on second line
- there isnt any validation on radio options, so if you dont select an option it takes you to change the date

Date change
- doesnt validate if the 'to' date being before the 'from' date

validation messages - can we use new error messages? - slides are being updated for other MBS forms types https://digitaleq.atlassian.net/wiki/spaces/EQ/pages/110854206/Error+messages+and+standard+text


summary 
for radio options can we remove the bullet point

**Review by charlotte-hirst — APPROVED** [review]
looks fine

**Review by charlotte-hirst — APPROVED** [review]

**Comment by collisdigital** [comment]
image
highlighting shouldn't be on trailing comma ,

**Comment by collisdigital** [comment]
image
Title shouldn't include "Retail Sales Index"

**Comment by collisdigital** [comment]
Got an error submitting with a comment:

```
eq-survey-runner_1     | Traceback (most recent call last):
eq-survey-runner_1     |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
eq-survey-runner_1     |     rv = self.dispatch_request()
eq-survey-runner_1     |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
eq-survey-runner_1     |     return self.view_functions[rule.endpoint](**req.view_args)
eq-survey-runner_1     |   File "/usr/local/lib/python3.4/site-packages/flask_login.py", line 792, in decorated_view
eq-survey-runner_1     |     return func(*args, **kwargs)
eq-survey-runner_1     |   File "/usr/src/app/app/views/questionnaire.py", line 120, in post_block
eq-survey-runner_1     |     return submit_answers(eq_id, form_type, collection_id, metadata, answer_store)
eq-survey-runner_1     |   File "/usr/src/app/app/views/questionnaire.py", line 228, in submit_answers
eq-survey-runner_1     |     message = convert_answers(metadata, g.schema_json, answer_store, path_finder.get_routing_path())
eq-survey-runner_1     |   File "/usr/src/app/app/submitter/converter.py", line 65, in convert_answers
eq-survey-runner_1     |     payload['data'] = convert_answers_to_data(answer_store, questionnaire_json, routing_path)
eq-survey-runner_1     |   File "/usr/src/app/app/submitter/converter.py", line 97, in convert_answers_to_data
eq-survey-runner_1     |     answer_data = _get_answer_data(data, answer_schema['q_code'], value)
eq-survey-runner_1     | KeyError: 'q_code'
```

**Comment by collisdigital** [comment]
image
 error message is wrong (see spec)

**Comment by collisdigital** [comment]
image

Error messages don't match spec

**Comment by collisdigital** [comment]
image

Error message content isn't to spec

**Comment by collisdigital** [comment]
image

Is there a way we can stop this (Bank Holiday) wrapping mid-word on the summary screen (applicable too all content, not just this particular answer)?

**Comment by collisdigital** [comment]
image

Display of dates aren't consistent here, sometimes it has '01 May' and others just '1 May', I checked with Sarah and Alison, it should always be '1 May' without any leading zeros.

**Review by collisdigital — CHANGES_REQUESTED** [review]
See comments

**Comment by jonnyshaw89** [comment]
@collisdigital I have addressed all your comments minus the error messages which i have raised a separate card for. https://trello.com/c/rSAVzIbO/1324-update-default-error-messages-and-remove-overrides-in-questionnaires

**Review by collisdigital — APPROVED** [review]

**Review by adoublebarrel — APPROVED** [review]
LGTM

**Pull request merged**
