### PR TITLE
Format all json schemas to be consistent

### PR DESCRIPTION
**Pull request by benjefferies**
### What is the context of this PR?
Schemas will be easier to modify if they are formatted consistently. It
makes copying blocks of json between schemas easier and overall easier
to read.

### How to review 
No functional changes so tests should be enough
Agree a common formatting configuration if not the pycharm default

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
@benjefferies maybe rebase to get the timeout retry?

**Comment by samiwel** [comment]
Did you use some kind of tool to get this formatting consistent across schemas? (I hope so) If yes, do we need to document/configure said tool to ensure that all future schemas are also consistent?

**Comment by benjefferies** [comment]
@samiwel just used the pycharm formatter. Click directory -> cmd + option + L. We could document it but everyone is using pycharm I guess?

**Review by jonnyshaw89 — APPROVED** [review]

**Comment by jonnyshaw89** [comment]
@benjefferies :1st_place_medal: on the PR #1000 prize!

**Review by samiwel — APPROVED** [review]

**Pull request merged**
