### PR TITLE
Census Individual: Changes to `accommodation-type` block

### PR DESCRIPTION
**Pull request by MebinAbraham**
### What is the context of this PR?
Makes `accommodation-type` block mandatory and removes redundant skip conditions.
Added question guidance as well.

### How to review 
Ensure:
- Changes are as per Trello.

[Quick launch for WLS schema](https://v3-launcher.gcp.dev.eq.ons.digital/quick-launch?language_code=en&survey=CENSUS&case_type=HI&region_code=GB-WLS&url=https://gist.githubusercontent.com/MebinAbraham/cfbb15194b07dcc0dd556a750b861e65/raw/5bc45f8a544237123b8f97f50438e0d60da93430/census_individual_gb_wls-pr-2210.json)

### CODE REVIEW

**Comment by MebinAbraham** [comment]
[Changes to question - all surveys (XS)](https://trello.com/c/bQkXK5D3/3157-changes-to-question-all-surveys-xs)

**Comment by charlotte-hirst** [comment]
Just double checking the routing after this question with donna otherwise it does what its supposed

**Review by charlotte-hirst — APPROVED** [review]
LGTM

**Review by bambrp — APPROVED** [review]
I am totally fine with this.

**Pull request merged**
