### PR TITLE
MWSS Production Schema

### PR DESCRIPTION
**Pull request by collisdigital**
### What is the context of this PR?
- Re-generated MWSS schema from latest Google Slides and merged the differences.
- Added all q_codes (from slides)
- Updated id values in schema to be more meaningful
- Added validation messages (based on previous questionnaires)
- Switched exercise dates to piped values from RRM

### Todo
- [x] Check validation message content is acceptable with DCM - confirmed with Emma Timm; all good.
- [x] Either support PositiveInteger question types displaying a `description` or agree with DCM to remove it from the schema (it currently doesn't display on question 2.10, 3.10, 4.10 etc. "Please enter the percentage or number of staff affected". - Confirmed with Emma Timm; removed content.
- [x] Rename the schema to match the RRM expected id_code (1_0005.json) - Confirmed this is the number.
- [x] Update survey_id and questionnaire_id in schema to correct values (are these used?)
- [x] Rebase and squash
- [x]  Pipe period string  (re-use period_str in the header) in place of [[PIPE MONTH YYYY]] placeholder; will require a code change. - Confirmed with Emma Timm - can use the Period String as suggested.
- [x] Happy path selenium test.
- [x] Code review

### CODE REVIEW

**Comment by yoganandkunche** [comment]
Front end QA in progress:

Please find below are the observations of validation error messages in MWSS:

Expected: Please provide a value, even if your value is 0.
Actual: This field is mandatory.

Expected: The maximum value allowed is 9999999999. Please correct your answer.
Actual: This number is too big.

Expected: The maximum value allowed is 100. Please correct your answer.
Actual: This number is too big.

Expected: Negative values are not allowed.
Actual: The value cannot be negative. Please correct your answer.

Expected: The date entered is not valid. Please correct your answer.
Actual: This is not a valid date.

Expected: The value you have entered is invalid. Please enter a numeric value.   (According to spec file - slide 19)
Actual: Please only enter whole numbers into the field.

**Comment by yoganandkunche** [comment]
*Issue:* Not getting a green tick under navigation after completion of 'General Comments' section

**Comment by yoganandkunche** [comment]
Extra bullet point for Q. 4.2 under 'Show further guidance' 

screen shot 2017-02-27 at 12 25 56

**Review by yoganandkunche — COMMENTED** [review]
Outstanding issues:
1) Issue: Not getting a green tick under navigation after completion of 'General Comments' section
2) Basis of completion (content) missing on the Landing page.

**Comment by yoganandkunche** [comment]
Retested following 'Add support for period_str' change looks good apart from the above mentioned issues.

**Comment by collisdigital** [comment]
@yoganandkunche :
- Basis for completion will be added on a separate card.
- I resolved the tick for General Comments section

**Comment by yoganandkunche** [comment]
@collisdigital Compared the q_codes in json against the spec file attached to the card in trello and everything matches and are as expected.
Re-tested mwss survey on the branch to confirm that the general comments sections get the completion tick - and it is Green.

**Comment by yoganandkunche** [comment]
@collisdigital Also tested the routing rules and everything is according to the spec file. I would say the only outstanding bit on this PR is code review.

**Review by ajmaddaford — APPROVED** [review]

**Comment by collisdigital** [comment]
Thanks @yoganandkunche

**Comment by collisdigital** [comment]
@ajmaddaford do you want this squashed down to 1 commit or split as current?

**Review by benjefferies — APPROVED** [review]

**Comment by benjefferies** [comment]
Squash and a rebase?

**Comment by collisdigital** [comment]
On it

**Pull request merged**
