### PR TITLE
Removing unused fields from state e.g. skip_condition

### PR DESCRIPTION
**Pull request by benjefferies**
### What is the context of this PR?
skip_condition is defined on various state items yet it is not ever referenced. Having state which isn't ever used is maintenance overhead and confusing. There are other fields which are defined by not referenced.

### How to review 
All tests should pass

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
Nice. Just a few codecov misses.

**Comment by benjefferies** [comment]
Deleting more code makes the codecov pass now @jonnyshaw89

**Review by ajmaddaford — APPROVED** [review]
Nice!

**Review by LJBabbage — CHANGES_REQUESTED** [review]
We use display for 2 colums at answer level, so we can't remove it without approval from the designers

**Comment by jonnyshaw89** [comment]
@hamishtaplin can you confirm what @LJBabbage is saying? do you guys use this?

**Review by LJBabbage — APPROVED** [review]

**Pull request merged**
