### PR TITLE
Add collapsible summary to MWSS and update pattern library to 1.5.6

### PR DESCRIPTION
**Pull request by dcdarrell9**
### What is the context of this PR?
- Add collapsible summary to MWSS

### How to review 
- Check MWSS summary contains accordions and is correct

### Checklist

* [ ] New static content marked up for translation
* [ ] Newly defined schema content included in eq-translations repo

### CODE REVIEW

**Review by insacuri — DISMISSED** [review]

**Review by jonnyshaw89 — DISMISSED** [review]
Doesn't scroll properly

**Comment by jonnyshaw89** [comment]
@boxadesign It appears as though the summary scrolls independently of the page. This make the page behave very strangely when scrolling

**Comment by boxadesign** [comment]
@jonnyshaw89 @dcdarrell9 I have fixed the issue with the summary component. To do this I had to also bring runner up to the latest version of the pattern library (v1.5.5). Version 1.5.3 had a small breaking change in it for the character counter in the textarea template (which I've fixed in my last commit)

**Review by bitdivision — APPROVED** [review]
Looks as I would expect.

**Review by MebinAbraham — APPROVED** [review]
Changes look fine, text area and collapsable summary working as expected. We should upgrade to cdn ver `1.5.6`, since that has just been released and it has no breaking changes.

**Comment by bitdivision** [comment]
Looks good still @dcdarrell9 .

**Pull request merged**
