### PR TITLE
Add new safe health check that doesn't disclose any system info

### PR DESCRIPTION
**Pull request by dhilton**
### Changes

To enable us to turn healthchecks on in production without disclosing any sensitive information.We have added a new health check url that hides any detailed issues and
merely returns OK or DOWN for a healthcheck request, with
associated http codes of 200 and 500 respectively.
### How to test
1. Run the app, check `/health` you should see a simple output of `OK`
2. Change the DEV_MODE environment variable
3. ReRun the app and check that you can't see `/health` and instead can see the current full healthcheck at `/healthcheck`
### Who can test

Anyone but @dhilton

### CODE REVIEW

**Comment by weapdiv-david** [comment]
I can't run this outside of dev mode as I don't have keys

**Comment by dhilton** [comment]
Can you modify your local version to trigger that scenario without having to generate a new set of encryption credentials? I realise this isn't a true test but given the change that will give a true reflection of the functionality added.

**Comment by weapdiv-david** [comment]
Right, got it!  The safe health check url is `/status` not `/health`, but I found it, I've seen it working, and I'm happy with it :)

**Comment by weapdiv-david** [comment]
LGTM :+1: Mergin'!

**Pull request merged**
