### PR TITLE
Add missing qcodes to UKIS

### PR DESCRIPTION
**Pull request by tgandrews**
### What is the context of this PR?
To resolve missing `qcodes` in UKIS

### How to review 
1. Ensure that the qcodes are used when selecting the answers.

### CODE REVIEW

**Comment by tgandrews** [comment]
[UKIS - 0440 & 2671 Qcodes to be added to Runner](https://trello.com/c/53uPoWiU/855-ukis-0440-2671-qcodes-to-be-added-to-runner)

**Review by jonnyshaw89 — APPROVED** [review]

**Review by samiwel — APPROVED** [review]
LGTM. Need to just confirm that this doesn't have any knock-on effect with SDX. @insacuri is this likely to cause you any problems?

**Review by insacuri — APPROVED** [review]
The changes look fine.  I do have a question though.  Are you pressed for time at the minute?  If so, then I'll approve it and you can merge it in as is, but if not, can you sort out the d codes so they start from 1?  It's a hassle but keeping this tidy for future people will be helpful as I'm sure the question of 'oh, why didn't they start from 1, how hard could it be?' will be asked

**Comment by insacuri** [comment]
And @samiwel this will 100% have a knock on effect with SDX as they're expecting those d codes and are doing something with it.  SDX will need some work

**Review by insacuri — CHANGES_REQUESTED** [review]
Changed my mind.  This should be done properly.  These chanages are fine but the other d codes need to be reordered

**Comment by samiwel** [comment]
Hey @insacuri can you explain what the d codes are used for? We can ensure that they appear in incremental order, but we're lacking knowledge about what they are used for and what is their purpose?

**Comment by tgandrews** [comment]
@insacuri Thanks for the feedback. I didn't know anything of dummy codes before. I've updated them so they increment correctly now but this changes it in a number of places is this what you expected?

**Review by insacuri — APPROVED** [review]

**Pull request merged**
