### PR TITLE
Renaming jenkins script for production and creating one for pre-prod

### PR DESCRIPTION
**Pull request by warrenbailey**
### Changes

Creating seperate jenkins scripts for prod and pre-prod. Also making the password of the DEV MODE rrm private configurable
### How to test
1. Deploy prod and pre-prod environments
### Who can test

@dhilton

### CODE REVIEW

**Comment by dhilton** [comment]
Can the bash scripts have explicit exit codes? That way we'll be able to know that a build set has explicitly failed or suceeded?

**Comment by warrenbailey** [comment]
I added !/bin/bash -e to the top of the scripts. This means the script will exit if one of the command fails and the jenkins job will then subsequently fail. Is that enough? or do you want me to catch the exit code from the commands and then terminate the script with a specific error code?

**Comment by dhilton** [comment]
Ah I didn't realise that worked. That's cool with me.

**Comment by dhilton** [comment]
LGTM 👍

**Pull request merged**
