### PR TITLE
Eq 1319 cookie and contact us pages

### PR DESCRIPTION
**Pull request by MIslam92**
### What is the context of this PR?
Addition of new static pages to survey runner i.e contact us page & cookies and privacy page

### How to review 
run ./scripts/run_app.sh and docker then navigate to url and append /contact-us or /cookies-privacy e.g. localhost:5000/contact-us to check that pages match design.
Yarn compile/start may be needed to run for styles.

### CODE REVIEW

**Comment by shahi645** [comment]
Should the behaviour of the footer, when clicking on the same information that the user is currently on...be to open a new tab with the same information? 

Maybe it should just direct you to the top of the page

**Comment by jonnyshaw89** [comment]
I think the padding on the tables on the cookies page is a bit insufficient?
screen shot 2017-09-07 at 11 17 27

**Comment by jonnyshaw89** [comment]
I think the line spacing is too big between the address lines.
screen shot 2017-09-07 at 11 29 34

**Comment by armstrongb** [comment]
@jonnyshaw89 agreed the lines of the address should be line breaks not paragraphs.

**Comment by armstrongb** [comment]
@MIslam92 can you try checking out the tables branch of the SDC Pattern library and compare with the proposed table style?

**Comment by MIslam92** [comment]
@armstrongb Yh I'll pull it down and have a look

**Comment by yoganandkunche** [comment]
@MIslam92 I am not sure whether it changed as part of this PR but the spacing seems to be a bit too big with in the company details section. 
**Actual:**
screen shot 2017-09-10 at 09 54 37

**Expected:**
screen shot 2017-09-10 at 09 55 29

**Comment by collisdigital** [comment]
image

The info that was in the header/banner is no longer available to the respondent:

image

Should this info be on the Contact Us page if available @charlotte-hirst

**Comment by collisdigital** [comment]
Spacing on mobile looks wrong on footer, talk with @armstrongb  :
image

**Review by jonnyshaw89 — APPROVED** [review]
Im happy that this meets the current acceptance criteria

**Review by shahi645 — APPROVED** [review]
LGTM, works locally, all tests pass and is responsive 👍🏿

**Comment by collisdigital** [comment]
Spacing on preview looks wrong now:

image

**Comment by collisdigital** [comment]
Actually lots of margin/padding issues all over the place, think this needs a visual check and review vs. current master as we're likely to miss something if not careful....

**Comment by MIslam92** [comment]
@collisdigital Just made the change should be fixed now across service

**Comment by jonnyshaw89** [comment]
@collisdigital can you confirm you are happy with the latest changes? if not can you add a blocking review?

**Comment by MIslam92** [comment]
Need this PR https://github.com/ONSdigital/eq-survey-runner/pull/1235 to be approved before we can merge this one please

**Comment by collisdigital** [comment]
Spacing still off here:

image

**Review by collisdigital — CHANGES_REQUESTED** [review]
Fix spacing first

**Comment by collisdigital** [comment]
Footer OGL doesn't look right on mobile:

image

**Comment by collisdigital** [comment]
Is this spacing correct on the mobile footer:

image

**Review by collisdigital — APPROVED** [review]

**Comment by collisdigital** [comment]
Looks good now

**Pull request merged**
