### PR TITLE
Deploy MWSS Content Changes

### PR DESCRIPTION
**Pull request by MIslam92**
### What is the context of this PR?
Change to using the updated MWSS content in `1_0005.json`

Card: https://trello.com/c/AytnMjGi/1838-deploy-mwss-content-changes

Related: https://github.com/ONSdigital/go-launch-a-survey/pull/49

### How to review 
Open `1_0005.json` and check that it is the updated version & it displays all the correct content in Runner.

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
Have you ensured there are other tests that check the downstream values of different field types?

**Comment by MIslam92** [comment]
@jonnyshaw89 By the looks of things in `test_converter.py` it checks the values for text areas and checkboxes.
Guess I should write some tests for other fields like radios etc.

**Review by nealedj — CHANGES_REQUESTED** [review]
Yeah it makes sense to remove schema tests but let's make sure we don't lose any test coverage.

It looks like test_converter is only checking its processing of field types that it actually needs to do some conversion on.

It should also check field types that it does nothing to in order to assert that their values get passed without any change:

- Radio
- Number
- Percentage
- TextArea
- Currency

**Review by nealedj — APPROVED** [review]

**Comment by nealedj** [comment]
Switching this to approved because there's some urgency to this change. Will raise the test coverage job separately.

**Review by jonnyshaw89 — APPROVED** [review]

**Pull request merged**
