### PR TITLE
Removing conditional dates and revert content from RSI and MCI surveys

### PR DESCRIPTION
**Pull request by MIslam92**
### What is the context of this PR?
- All RSI and MCI types are reverted to their previous versions

- All survey launch pages for RSI and MCI types are reverted to their previous versions

See also: #1208, #1210

### How to review 
Launch all RSI & MCI surveys and compare that they all match previous version
Surveys:
0102
0112
0203
0205
0213
0215

### CODE REVIEW

**Review by charlotte-hirst — APPROVED** [review]
Checked all surveys are working but does need someone like @yoganandkunche to carefully check them side by side as we cant take any chances with RSI

**Review by yoganandkunche — APPROVED** [review]
@charlotte-hirst Looks good to me. I will be review this again in pre-prod and verify the .pck files which go downstreams.

**Comment by yoganandkunche** [comment]
@jonnyshaw89 could you please review it code wise.

**Review by jonnyshaw89 — CHANGES_REQUESTED** [review]
It looks like some of the blocks have `id` defined twice. if you can remove the duplicate then I'm happy

**Review by jonnyshaw89 — APPROVED** [review]

**Pull request merged**
