### PR TITLE
Fixes Census Household Name piping on 'Your household includes' page

### LINKED ISSUE #906: Census: Entering more than 25 people to households displays everyone on 'Your household includes:' screen
### Expected behaviour
Must only display 25 people on 'Your household includes:' and on the Navigation panel

### Actual behaviour
Displays list of all the people added on the 'Your household includes:' page (PFA)

### Steps to reproduce the behaviour
Launch Census Household schema
Add more than 25 people to the household and 
Navigate to 'Your household includes:' screen

### Screenshot
screen shot 2017-01-31 at 14 46 13

### PR DESCRIPTION
**Pull request by yoganandkunche**
### What is the context of this PR?
Fixes #906 

### How to review 
Retest defect #906

Launch Census Household schema
Add more than 25 people to the household and
Navigate to 'Your household includes:' screen
Must only display 25 people on 'Your household includes:' and on the Navigation panel

### CODE REVIEW

**Review by benjefferies — CHANGES_REQUESTED** [review]
Commit message should describe what is being fixed and why as well as the reference to the issue. Also lacking test coverage to catch regressions

**Review by benjefferies — APPROVED** [review]
This looks fine as a quick fix but we should probably look into this further as discussed. Should we have validation to limit the number of repeats rather than allow the number to be entered but repeat 25 number of times

**Comment by yoganandkunche** [comment]
@benjefferies yeah that solution was discussed with @collisdigital and @ajmaddaford but for this MVP we are only fixing this defect.

**Review by samiwel — APPROVED** [review]
Longer term we probably need to find some way of limiting the number of answer instances in the answer store, but for now this seems like a reasonable fix.

**Comment by samiwel** [comment]
@yoganandkunche Please can you update your branch from master and squash the commits?

**Comment by yoganandkunche** [comment]
@samiwel I have update the branch and did squash commit. can you please press the magic button.

**Pull request merged**
