### PR TITLE
Fix UKIS navigation

### LINKED ISSUE #1079: UKIS: Clicking on 'General Business Information' navigation link navigates to Landing page
### Expected behaviour
Must navigate to 'General Business Information' section

### Actual behaviour
Navigating to Landing page.

### Steps to reproduce the behaviour
launch UKIS survey
Answer few sections and
click on 'General Business Information' navigation link
### Screenshot
screen shot 2017-04-03 at 11 47 29

### PR DESCRIPTION
**Pull request by LJBabbage**
### What is the context of this PR?
Fixes #1079 by making introduction into its own group

### How to review 
rest #1079

### CODE REVIEW

**Comment by collisdigital** [comment]
Please verify that someone on the previous schema who has partially completed won't be directed back to the Introduction when attempting to submit

**Comment by LJBabbage** [comment]
Yep, that is an issue @collisdigital ,however there is no way around it. Marking it as in-progress until we decide what we want to do

**Comment by collisdigital** [comment]
@ajmaddaford turns out the completed blocks also contains the group-id and instance-id to deal with repeating; so moving the intro into it's own group means it isn't in the completed blocks for in-progress users. If they sign back in after this change they will be taken to the intro; anyone already signed-in will get taken back when attempting to submit.

**Comment by collisdigital** [comment]
Won't fix due to the issues it will introduce.

**Pull request closed without merging**
