### PR TITLE
fix typevalidatorfactory.py

### PR DESCRIPTION
**Pull request by weapdiv-david**
### Changes

Fixes a typo in the TypeValidatorFactory
### How to test

1) Checkout the branch
2) Run the unit tests
### Who can test

Anyone except @weapdiv-david

### CODE REVIEW

**Comment by collisdigital** [comment]
This could be a good opportunity to switch to app/utilities/factory.py pattern?

**Comment by weapdiv-david** [comment]
I think this is a good opportunity to look at the software design as a whole.  With validation coming up and question types / response types research done, it might be a good time to clean a lot of this up

**Comment by weapdiv-david** [comment]
Nice refactor. Do we need someone else to review it now?

**Comment by dhilton** [comment]
Happy for it to merge if you are 👍

**Pull request merged**
