### PR TITLE
Add a minimum exclusive value of 0 to total pay for each pay pattern

### PR DESCRIPTION
**Pull request by shahi645**
### What is the context of this PR?
For each pay patterns total gross pay, the user may now no longer enter 0 as a value.

### How to review 
Run MWSS try total pay with `0` in each pay patter. Should give the correct validation error

### CODE REVIEW

**Review by yoganandkunche — DISMISSED** [review]
@shahi645 the validation error messages need tweaking. When no value entered on mandatory field the app gives a validation error message : Enter an answer, even if it is 0. when entering '0' is not a valid entry

**Comment by shahi645** [comment]
@yoganandkunche will look at this

**Comment by jonnyshaw89** [comment]
@shahi645 This can't really be reviewed until we have the validator change

**Comment by shahi645** [comment]
@jonnyshaw89 the fix can be reviewed, to see if it works.

**Review by MIslam92 — APPROVED** [review]

**Review by ajmaddaford — APPROVED** [review]

**Pull request merged**
