### PR TITLE
added touch icons

### LINKED ISSUE #1052: Missing icons for apple devices
### Expected behaviour
We shouldn't get 404s for missing apple touch icons

### Actual behaviour
Web server has 404 errors for:
```
apple-touch-icon-152x152-precomposed.png
apple-touch-icon.png
```

### Steps to reproduce the behaviour
Visit the service using an iPad and add it as a favourite

### PR DESCRIPTION
**Pull request by bennpearson**
### What is the context of this PR?
Fixes #1052 

### How to review 
Check touch icons appear on mobile devices.
Check for any 404s

### CODE REVIEW

**Comment by collisdigital** [comment]
Can these be generated at build time or are they manually created?

**Comment by bennpearson** [comment]
Yes these can be generated using this: https://www.npmjs.com/package/gulp-mobile-icons which we could add if touch icons become theme related

**Review by hamishtaplin — APPROVED** [review]

**Review by ajmaddaford — DISMISSED** [review]
I tried on BrowserStack using Safari on an iPad Air 2.
- Selecting on the 'export' button, a successful request is made for `/s/img/apple-touch-icon-152x152.png` 
- On selecting the 'Add Bookmark' an unsuccessful request (401 Unauthorised) is made to the current page:
```
{
	"url": "http://localhost/questionnaire/1/0102/m8dYqqGC/rsi/0/reporting-period",
	"event": "an error has occurred",
	"status_code": 401,
	"exception": [
		"Traceback (most recent call last):", 
		"  File '/usr/local/lib/python3.4/site-packages/flask/app.py', line 1473, in full_dispatch_request", 
		"    rv = self.preprocess_request()", 
		"  File '/usr/local/lib/python3.4/site-packages/flask/app.py', line 1666, in preprocess_request", 
		"    rv = func()", "  File '/usr/local/lib/python3.4/site-packages/flask_login.py', line 791, in decorated_view", 
		"    return current_app.login_manager.unauthorized()", 
		"  File '/usr/local/lib/python3.4/site-packages/flask_login.py', line 215, in unauthorized", 
		"    abort(401)", 
		"  File '/usr/local/lib/python3.4/site-packages/werkzeug/exceptions.py', line 646, in __call__", 
		"    raise self.mapping[code](*args, **kwargs)", "werkzeug.exceptions.Unauthorized: 401: Unauthorized"
	],
	"level": "error",
	"request_id": "24632fba-12ff-41a1-85ce-59eeebacd00b",
	"service": "eq-survey-runner",
	"created": "2017-03-29T15:14:33.507340Z"
}
```
image
  The icon doesn't appear in the dialog, and isn't present on the bookmarked pages screen after adding it.
- On selecting 'Add to Home Screen' the icon has a black background
image

**Comment by collisdigital** [comment]
Discussing with @ajmaddaford we should look to use the ONS CDN to serve the icons and also in that case sync up with DP @ian-kent and co to have one set of ONS icons we can use across all devices.

**Comment by bennpearson** [comment]
Think icons along with a manifest.json and browserconfig.xml file need to go in the root.

**Comment by ajmaddaford** [comment]
We can do this via the Elastic Beanstalk Apache config:
`AliasMatch ^/apple-touch-icon(.*).png /opt/python/current/app/static/img/apple-touch-icon.png`

This would also allow us to server `browserconfig.xml` and `manifest.json` from `/`

**Review by jonnyshaw89 — APPROVED** [review]

**Comment by jonnyshaw89** [comment]
@bennpearson or @ajmaddaford Squash and Rebase?

**Pull request merged**
