### PR TITLE
Upgrade Pattern Library to v1.8.2

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
Upgraded to latest version

### How to review 
Does it all still work as expected?

### CODE REVIEW

**Comment by bitdivision** [comment]
We're not using the welsh version of the ONS logo. Not sure if that should block this or not. https://github.com/ONSdigital/sdc-global-design-patterns/pull/200

**Review by bitdivision — APPROVED** [review]
Tested all the PL changes.

**Review by dwyeradam — APPROVED** [review]
Tried to test a broad range and didn't find anything.

**Comment by jonnyshaw89** [comment]
Superceeded by https://github.com/ONSdigital/eq-survey-runner/pull/1879

**Pull request closed without merging**
