### PR TITLE
Submit survey at end of routing path

### PR DESCRIPTION
**Pull request by jonnyshaw89**
### What is the context of this PR?
When the end of the routing path is reached submit the survey.

### How to review 
Does the survey still submit data when expected

### CODE REVIEW

**Review by benjefferies — APPROVED** [review]

**Review by samiwel — APPROVED** [review]
LGTM but needs rebasing.

**Comment by jonnyshaw89** [comment]
I think @ajmaddaford has some views on this so will hold it until he has reviewed.

**Comment by benjefferies** [comment]
Rebase?

**Comment by ajmaddaford** [comment]
In this approach I have concerns over implicitly submitting a users answers when we decide the end of the survey (routing path) is reached. I think this should only be done when the user has performed an action to submit their answers e.g. clicking a 'submit answers' button. After discussing with Jon we've come up with a hybrid solution - make the submit button on any page we determine to be at the end of the routing path a 'submit answers' button and look for this in the POST request.

**Review by ajmaddaford — CHANGES_REQUESTED** [review]
Needs adapting to the solution we discussed.

**Comment by ajmaddaford** [comment]
After further discussions with @benjefferies the new proposal is that we submit the survey when there is no next location **and** the current location block is of type `Summary` or `Confirmation`. This will give us confidence the user is at the end of the survey and allows us to make the default action on POST to be 'Save and continue' or 'Submit answers'. This also means that the `action[x]` buttons will only be needed for additional submit buttons on a page (e.g. adding/removing household members in the Census or 'Save and complete later').

**Review by ajmaddaford — APPROVED** [review]

**Comment by jonnyshaw89** [comment]
@ajmaddaford didn't want me to squash?

**Pull request merged**
