### PR TITLE
Fix descriptions on mutually exclusive checkbox and prepare for "checked" parameter

### PR DESCRIPTION
**Pull request by bameyrick**
Fixes descriptions not showing on the mutually exclusive checkbox, and prepares to accept a "checked" parameter. I can't seem to see if runner stores if a user selects the mutually exclusive option.

### CODE REVIEW

**Comment by bameyrick** [comment]
By upgrading from design system 6.0.1 to 8.0.4 this has caused tests to fail, however I've already fixed this in #2090, so ideally that needs merging first.

**Review by bitdivision — APPROVED** [review]
Seems to work :+1:

**Review by iwootten — CHANGES_REQUESTED** [review]
I'm unable to get this description to show when adding it to test_mutually_exclusive.json. I wonder if it might be an idea to add an example in there as part of the PR ?

**Comment by bitdivision** [comment]
Worked for me with: 
```                        
                        "id": "checkbox-exclusive-answer",
                        "mandatory": false,
                        "type": "Checkbox",
                        "options": [{
                            "label": "I prefer not to say",
                            "description": "Some description",
                            "value": "I prefer not to say"
                        }]

```

But I would agree, the description should be added to the test schema.

**Comment by iwootten** [comment]
@bitdivision Looks like I hadn't rebuilt my data sources - is working now.

**Review by bambrp — APPROVED** [review]
Works for me

**Review by iwootten — APPROVED** [review]

**Pull request merged**
