### PR TITLE
Removed Northern Ireland from introductions of mbs 817 and 867

### PR DESCRIPTION
**Pull request by AndrewTorrance**
### What is the context of this PR?
Remove the reference to Northern Ireland in use of information section of the Introduction for several surveys as mentioned on the trello card

### How to review 
View each survey. 

https://trello.com/c/WWan8FIg

### CODE REVIEW

**Review by dwyeradam — CHANGES_REQUESTED** [review]
`mbs_106.json` is missing Northern Ireland and it's not one of the form types specified on the card. 
Since you're making changes `mbs_123.json` and `mbs_173.json` are missing full stops at the end of the sentence.

**Comment by dwyeradam** [comment]
@AndrewTorrance I wouldn't bother putting this in the mbs-feature branch now. We'll want to merge this directly into master. Also feel free to squash at the same time as making my requested changes as they are easily tracked and we can merge quicker.

**Comment by AndrewTorrance** [comment]
106 should not have Northern Ireland , added to ticket. Fulls stops are missing , but I have picked that up as part of eq 2062 so I'd like to not do it here .

**Review by dwyeradam — APPROVED** [review]

**Review by MebinAbraham — APPROVED** [review]
👍

**Pull request merged**
