### PR TITLE
Add JSON to demo radio and checkbox description text

### PR DESCRIPTION
**Pull request by ajmaddaford**
### What is the context of this PR?

Adds a new survey JSON to demo the feature implemented in https://github.com/ONSdigital/eq-survey-runner/pull/471
### How to review
- Go to the dev page
- Select the test_radio_checkbox_descriptions.json schema
- Complete survey and verify the appropriate checkbox and radio option labels appear on the summary page (not the description text)

### CODE REVIEW

**Review by iwootten — COMMENTED** [review]
I added these things to the main star wars survey too, which you can see here: https://github.com/ONSdigital/eq-survey-runner/pull/471/files#diff-897b2600a7ceefe3249c642a9c9e81b2R57 should they be removed from there?

**Review by iwootten — COMMENTED** [review]
I feel if we're adding lots of test schemas, they probably should exist separately in another folder from the main surveys.

**Comment by ajmaddaford** [comment]
We're going to have a discussion today about tests and test data, so we'll review this after that.

**Comment by benjefferies** [comment]
I'm happy with this to go in as is. I think we need a strategy for test schemas going forward. We have a backlog item for this - https://trello.com/c/z9iikwAZ/271-create-a-separation-for-business-survey-configuration-and-test-survey-configuration

**Review by benjefferies — APPROVED** [review]

**Pull request merged**
