### PR TITLE
Fixes #929 text missing from above currency input.

### LINKED ISSUE #939: UKIS: Text missing from above all £ value fields.
### Expected behaviour
screen shot 2017-02-13 at 15 42 06

### Actual behaviour
screen shot 2017-02-13 at 15 41 17

### Steps to reproduce the behaviour
Launch UKIS survey
Navigate to all the £ value entering fields
#### Browser
Chrome

### PR DESCRIPTION
**Pull request by samiwel**
### What is the context of this PR?
Fixes #939.

### How to review 
Re-test the defect and confirm that the description text is displayed.
All existing tests should continue to pass.

### CODE REVIEW

**Comment by yoganandkunche** [comment]
Defect passed on branch.

**Comment by samiwel** [comment]
@yoganandkunche Does this only affect currency inputs for UKIS? If other input types are affected I'll need to make some more changes.

**Review by LJBabbage — COMMENTED** [review]
Works fine, however content is being clarified, so hold for the moment

**Comment by yoganandkunche** [comment]
@samiwel Yes the issue is only with the currency fields.

**Review by hamishtaplin — APPROVED** [review]

**Review by iwootten — APPROVED** [review]

**Pull request merged**
