### PR TITLE
Saucelabs/Travis Integration

### PR DESCRIPTION
**Pull request by hamishtaplin**
### Changes
- Adds configuration for [Webdriver.io](http://webdriver.io/) and [Mocha](http://mochajs.org).
- Remote browser testing via [Sauce Labs](https://saucelabs.com) on all desktop browsers (except MS Edge).
- Adds a functional test for MCI survey that ensures survey can be completed in all desktop browsers.
- Integration for Travis to run functional tests as part of CI.
- Adds three new npm commands for running tests:
  - `npm run test_functional` runs functional tests through Sauce Labs.
  - `npm run test_functional_local` quickly runs functional tests through via a local Selenium instance.
  - `npm run test_unit` runs just unit tests through Karma.
### How to test
- `npm install` new dependencies.
- `npm run test_functional_local` will spin up a Selenium server and run a single test.
- `npm run test_functional` will connect to Sauce Labs and tunnel instance of app running on `http://localhost:5000` to test. 
### Who can test
- Anyone

### CODE REVIEW

**Comment by dhilton** [comment]
If the Travis integration is causing too much pain - can we split that out, merge the functional tests and then attack the Travis integration in a separate PR? Cause this is really good stuff.

**Comment by hamishtaplin** [comment]
@dhilton Yeah I'm thinking that is going to be the best solution for now, as it's behaving very strangely. If the next build fails, I can whip the travis integration out and run the tests manually which works much more reliably.

**Comment by hamishtaplin** [comment]
Marking this as WIP again as latest changes in master break the tests.

**Comment by dhilton** [comment]
I think we probably need to add something to the Readme about how to run these tests and possibly have the test run start the application when running locally, as I hadn't realised you needed the server running to run the tests.

**Comment by hamishtaplin** [comment]
@dhilton I have updated the readme with a quick note on needing the app running

**Pull request merged**
