### PR TITLE
Content changes for Stocks

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
This PR is for some more content changes to stocks. Rewording, removing bullet points etc

### How to review 
Survey launches and looks ok

### CODE REVIEW

**Comment by rmccar** [comment]
[2. Stocks Change Required from CAT Testing](https://trello.com/c/I0a8pKVn/1138-2-stocks-changes-required-from-cat-testing)

**Comment by rmccar** [comment]
[3. Stocks Change Required from CAT Testing](https://trello.com/c/36qLHuFk/1139-3-stocks-changes-required-from-cat-testing)

**Comment by rmccar** [comment]
[4. Stocks Change Required from CAT Testing](https://trello.com/c/WauMvUFk/1140-4-stocks-changes-required-from-cat-testing)

**Comment by rmccar** [comment]
[5. Stocks Change Required from CAT Testing](https://trello.com/c/nOVEKrFW/1141-5-stocks-changes-required-from-cat-testing)

**Comment by rmccar** [comment]
[1. Stocks Change Required from CAT Testing](https://trello.com/c/jNJRnW8E/1137-stocks-changes-required-from-cat-testing)

**Review by SamGodwin2 — APPROVED** [review]

**Review by heofs — APPROVED** [review]

**Pull request merged**
