### PR TITLE
Migrate UKIS Functional Test 

### PR DESCRIPTION
**Pull request by yoganandkunche**
### What is the context of this PR?
Migrates UKIS happy path functional test to new_functional.

### How to review 
Run:  BASEURL=http://localhost:5000 ./node_modules/.bin/wdio tests/new_functional/wdio.conf.js --spec tests/new_functional/spec/ukis.spec.js

### CODE REVIEW

**Comment by shahi645** [comment]
i have a bunch of UKIS routing tests still in my functional folder, is that supposed to be the case?

**Comment by yoganandkunche** [comment]
@shahi645 Yes this PR is only for the happy path e2e test.

**Review by jonnyshaw89 — APPROVED** [review]

**Review by dwyeradam — APPROVED** [review]
All fine. We'll also need to look at the tests in tests/functional/spec/ukis/routing/ so that we can get rid of all the page files as well.

**Comment by jonnyshaw89** [comment]
@yoganandkunche Squishy Squashy?

**Pull request merged**
