### PR TITLE
Fix routing bug in UKIS questionnaire.

### PR DESCRIPTION
**Pull request by samiwel**
### What is the context of this PR?
The requirement is to skip to question 10 as per the slides, but it was previously skipping to 9.11.

Refactor to use skip condition on the group as it's cleaner than having routing rules on the interstitial page.

### How to review 
UKIS routing should be tested to ensure it works as expected.

### CODE REVIEW

**Review by jonnyshaw89 — APPROVED** [review]

**Review by dwyeradam — APPROVED** [review]
Can we get this applied to the NI version as well.

**Review by dwyeradam — CHANGES_REQUESTED** [review]
Can we get this applied to the NI version as well.

**Review by dwyeradam — CHANGES_REQUESTED** [review]
Can we get this applied to the NI version as well.

**Review by dwyeradam — DISMISSED** [review]
Can we get this applied to the NI version as well.

**Review by dwyeradam — APPROVED** [review]

**Comment by dwyeradam** [comment]
@samiwel just needs a squash and rebase.

**Pull request merged**
